function choice(label, preview, opts = {}) { return { label, preview, ...opts }; }

const baseStatLabels = {
  health: 'Health', hunger: 'Hunger', hydration: 'Hydration', energy: 'Energy', willToLive: 'Will to Live', trust: 'Trust',
  personalEscapeAdvantage: 'Personal Escape Advantage', personalFinalBonus: 'Personal Final Bonus', helpedGroup: 'Helped Group', betrayals: 'Betrayals', cluesFound: 'Clues Found', riskActions: 'Risk Actions'
};

const baseGroupLabels = {
  campSafety: 'Camp Safety', fire: 'Fire', foodSupply: 'Food Supply', waterSupply: 'Water Supply', escapeProgress: 'Escape Progress',
  threatAwareness: 'Threat Awareness', cluesFound: 'Clues Found', finalEncounterBonus: 'Final Bonus', hiddenThreatLevel: 'Hidden Threat Level', trustPressure: 'Trust Pressure'
};

const defaultOutcomes = {
  full: 'Full Rescue', broken: 'Broken Rescue', partial: 'One or Two Survive', wounded: 'The Threat Wins, But One Escapes Wounded', lost: 'Everyone Is Lost'
};

function mkEpisode(def) {
  const episode = {
    ...def,
    maxRounds: def.maxRounds || 6,
    modes: { standard: 'Standard · 55 minutes', quick: 'Quick · 35 minutes', long: 'Long · 75 minutes', ...(def.modes || {}) },
    statLabels: { ...baseStatLabels, ...(def.statLabels || {}) },
    groupStatLabels: { ...baseGroupLabels, ...(def.groupStatLabels || {}) },
    outcomes: { ...defaultOutcomes, ...(def.outcomes || {}) }
  };
  episode.privateCards = makePrivateCards(episode);
  return episode;
}

function makePrivateCards(ep) {
  const resource = ep.cardWords?.resource || 'hidden supplies';
  const tool = ep.cardWords?.tool || 'useful tool';
  const signal = ep.cardWords?.signal || 'signal piece';
  const clue = ep.cardWords?.clue || 'strange mark';
  const place = ep.cardWords?.place || 'dark corner';
  const threat = ep.finalThreat || 'the threat';
  const cards = {};
  for (let r = 1; r <= 6; r++) {
    const round = ep.rounds[r - 1];
    cards[r] = [
      { id: `${ep.id}-r${r}c1`, title: `Hidden ${cap(resource)}`, type: 'Resource Secret', text: `You quietly find ${resource} during ${round.title}. No one else sees it.`, reveal: { foodSupply: 1, trust: 1 }, hide: { hunger: 2, trust: -1 }, trade: { personalEscapeAdvantage: 1 }, selfish: { hunger: 2, hiddenThreat: 1 } },
      { id: `${ep.id}-r${r}c2`, title: 'Private Weakness', type: 'Personal Weakness', text: `The pressure is getting to you. You can admit it, hide it, or use it to manipulate the group.`, reveal: { willToLive: -1, trust: 1 }, hide: { willToLive: -1 }, trade: { trust: 1 }, selfish: { trust: -1, personalFinalBonus: 1 } },
      { id: `${ep.id}-r${r}c3`, title: `The ${cap(tool)}`, type: 'Useful Tool', text: `You find a ${tool}. It could help the group, or it could become your backup plan.`, reveal: { campSafety: 1, trust: 1 }, hide: { personalFinalBonus: 1, trust: -1 }, trade: { trust: 1 }, selfish: { personalFinalBonus: 2, hiddenThreat: 1 } },
      { id: `${ep.id}-r${r}c4`, title: 'Suspicious Move', type: 'Suspicion', text: `You notice someone acting strange near ${place}. You are not sure if they are scared, selfish, or dangerous.`, reveal: { threatAwareness: 1 }, hide: { willToLive: -1 }, trade: { personalEscapeAdvantage: 1 }, selfish: { trust: -1, hiddenThreat: 1 } },
      { id: `${ep.id}-r${r}c5`, title: `Damaged ${cap(signal)}`, type: 'Escape Secret', text: `You discover a damaged ${signal}. Used correctly, it could move everyone closer to the ending.`, reveal: { escapeProgress: 1, trust: 1 }, hide: { personalEscapeAdvantage: 1, trust: -1 }, trade: { personalEscapeAdvantage: 1 }, selfish: { personalEscapeAdvantage: 2, hiddenThreat: 1 } },
      { id: `${ep.id}-r${r}c6`, title: 'The Pattern', type: 'Clue Discovery', text: `You find ${clue}. It suggests ${threat} is responding to division inside the group.`, reveal: { cluesFound: 1, threatAwareness: 1, trust: 1 }, hide: { personalFinalBonus: 1, willToLive: -1 }, trade: { personalFinalBonus: 1 }, selfish: { personalFinalBonus: 1, hiddenThreat: 1 } }
    ];
  }
  return cards;
}

function cap(s) { return String(s).replace(/^./, c => c.toUpperCase()); }

const episodes = {
  island: mkEpisode({
    id: 'island', title: 'Island Survivor', subtitle: 'Episode 1', tagline: 'Survive the island. Survive each other. Find what is watching before it finds you.', venueDefault: 'Barfly Social Island Survivor', createButton: 'Create Island', joinVerb: 'Enter Island', playerNoun: 'Survivor', groupName: 'Camp', chatTitle: 'Camp Chat', systemAlias: 'Island', finalThreat: 'The Watcher', finalIntroTitle: 'It Found You', finalIntroText: 'The fire dies. The trees go silent. Then every survivor hears the same thing: footsteps circling the camp. The island was never empty. The Watcher has been studying you since the crash.', cardWords: { resource: 'food pack', tool: 'survival knife', signal: 'radio piece', clue: 'strange footprints', place: 'the tree line' },
    roles: [
      { id: 'medic', name: 'Medic', ability: 'Field Treatment', description: 'Softens injury damage and keeps survivors alive.' },
      { id: 'builder', name: 'Builder', ability: 'Structural Fix', description: 'Adds progress to shelter, raft, and trap actions.' },
      { id: 'scout', name: 'Scout', ability: 'Safe Path', description: 'Risk actions have better clue chance and lower injury chance.' },
      { id: 'hunter', name: 'Hunter', ability: 'Forage / Guard', description: 'Protects camp supplies or adds food when helping.' },
      { id: 'negotiator', name: 'Negotiator', ability: 'Calm the Camp', description: 'Repairs trust damage and keeps people together.' },
      { id: 'skeptic', name: 'Skeptic', ability: 'Read the Signs', description: 'Improves truth-finding and detects false assumptions.' }
    ],
    rounds: [
      { number: 1, title: 'The Crash', publicEvent: 'The survivors wake up on the beach after a wreck. Supplies are scattered. Some people are injured. Night is coming.', groupGoal: 'Build a first camp and survive the night.', choices: { help_group: choice('Build First Camp','Camp Safety may rise. Trust rises. Energy drops.',{energyCost:1,groupStat:'campSafety',groupGain:1}), help_self: choice('Search Wreckage Privately','You may gain a hidden item. Trust may fall if discovered.',{personalStat:'energy',personalGain:1,trustCost:1,hiddenItem:'Wreckage Supply'}), take_risk: choice('Go Inland Before Dark','Chance to find water or a clue, but you may be injured.',{energyCost:2,clueText:'Strange footprints appear near the tree line.',rewardStat:'waterSupply',rewardGain:1,injuryChance:.30,clueChance:.50}) }, teamBonus:{threshold:3,stat:'campSafety',amount:1,text:'Enough survivors worked together to make the first camp safer.'}, failure:{threshold:1,stat:'campSafety',amount:-1,text:'Too few survivors worked on camp. The first night feels exposed.'} },
      { number: 2, title: 'Water Crisis', publicEvent: 'The heat is brutal. The group’s water is almost gone.', groupGoal: 'Find clean water quickly.', choices: { help_group: choice('Search for Fresh Water','Water Supply may rise. Trust rises. Energy drops.',{energyCost:1,groupStat:'waterSupply',groupGain:1}), help_self: choice('Drink from Personal Stash','Hydration rises. Trust may fall.',{personalStat:'hydration',personalGain:2,trustCost:1}), take_risk: choice('Drink from Unknown Stream','Hydration may rise, but sickness or a clue is possible.',{energyCost:1,personalStat:'hydration',personalGain:2,injuryChance:.40,clueChance:.50,clueText:'Old carved symbols sit near the stream. They do not look random.'}) }, teamBonus:{threshold:3,stat:'waterSupply',amount:2,text:'The group found a reliable water source together.'}, failure:{threshold:1,stat:'waterSupply',amount:-1,text:'The water problem gets worse because almost no one searched.'} },
      { number: 3, title: 'The Storm', publicEvent: 'A storm rolls in. The shelter may collapse. The fire is almost out.', groupGoal: 'Protect camp before the storm hits.', choices: { help_group: choice('Reinforce Shelter','Camp Safety may rise. Trust rises. Energy drops.',{energyCost:2,groupStat:'campSafety',groupGain:1}), help_self: choice('Protect Personal Supplies','Personal supplies are protected. Trust may fall.',{personalStat:'hunger',personalGain:1,trustCost:1}), take_risk: choice('Save Supplies from the Wreck','Food, tools, or clues may be found. Injury risk is high.',{energyCost:2,rewardStat:'foodSupply',rewardGain:2,injuryChance:.40,clueChance:.50,clueText:'Lightning reveals a figure standing at the edge of the trees.'}) }, teamBonus:{threshold:3,stat:'campSafety',amount:2,text:'The shelter held and the fire stayed alive.'}, failure:{threshold:2,stat:'fire',amount:-1,text:'Too few survivors reinforced camp. The fire struggled in the storm.'} },
      { number: 4, title: 'Missing Supplies', publicEvent: 'Morning comes. Food is missing. Someone may have stolen it — or something entered camp overnight.', groupGoal: 'Find out what happened without destroying trust.', choices: { help_group: choice('Investigate Together','Threat Awareness may rise. Trust rises. Energy drops.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}), help_self: choice('Accuse Another Player','You may gain influence, but false accusations damage trust.',{personalStat:'willToLive',personalGain:1,trustCost:1}), take_risk: choice('Follow Tracks Alone','Possible major clue, possible attack.',{energyCost:2,injuryChance:.40,clueChance:.60,clueText:'The tracks circle the camp. They are not animal tracks.'}) }, teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'A group investigation found evidence that the island is not empty.'}, failure:{threshold:1,stat:'trustPressure',amount:1,text:'Without a real investigation, suspicion spreads.'} },
      { number: 5, title: 'Signs of Something Else', publicEvent: 'The raft has been damaged. No storm hit it. No animal tracks are nearby.', groupGoal: 'Repair the escape plan and understand what is hunting you.', choices: { help_group: choice('Repair the Raft','Escape Progress may rise. Trust rises. Energy drops.',{energyCost:2,groupStat:'escapeProgress',groupGain:1}), help_self: choice('Hide Escape Supplies','Personal escape advantage rises, but the group suffers if discovered.',{personalEscapeGain:2,groupStat:'escapeProgress',groupLoss:1,trustCost:2}), take_risk: choice('Search the Cave','Threat Awareness and clues may rise. Injury risk is high.',{energyCost:2,groupStat:'threatAwareness',groupGain:2,injuryChance:.40,clueChance:.50,clueText:'Names are scratched into the cave wall. Some are crossed out. Some are recent.'}) }, teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The raft repair surged forward because the group worked together.'}, failure:{threshold:1,stat:'escapeProgress',amount:-1,text:'The raft remains badly damaged.'} },
      { number: 6, title: 'Escape Attempt', publicEvent: 'The weather clears. Rescue may be possible. But the island feels different now. Something is close.', groupGoal: 'Prepare to escape or prepare to fight.', choices: { help_group: choice('Finish Escape Plan','Escape Progress rises. Trust rises. Energy drops.',{energyCost:2,groupStat:'escapeProgress',groupGain:2}), help_self: choice('Prepare to Escape Alone','Personal escape advantage rises. Group trust suffers.',{personalEscapeGain:2,trustCost:2}), take_risk: choice('Set a Trap','Final Encounter Bonus may rise, but injury is possible.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The Watcher has been studying every betrayal and waiting for the group to weaken itself.'}) }, teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The escape plan is ready because enough survivors committed to it.'}, trapBonus:{threshold:2,amount:2,text:'The final trap is stronger because multiple survivors helped set it.'} }
    ],
    finalChoices: {
      fight_together: { label:'Fight Together', description:'Best if enough survivors remain and trust is high.' }, set_trap:{ label:'Set the Trap', description:'Best if clues and trap bonuses were earned.' }, run_raft:{ label:'Run for the Raft', description:'Best if escape progress is high.' }, sacrifice:{ label:'Sacrifice Yourself', description:'May save others, but could eliminate you.' }, betray_group:{ label:'Betray the Group', description:'May help you escape alone, but can doom everyone.' }
    },
    outcomes: { full:'Full Rescue', broken:'Broken Rescue', partial:'One or Two Survive', wounded:'The Watcher Wins, But One Escapes Wounded', lost:'The Island Wins' },
    endingTexts: { full:'The survivors held the line together. The trap worked. The raft launched as first light hit the water. The island kept its secrets, but not its victims.', broken:'The survivors escaped, but not cleanly. The Watcher was slowed, not beaten. The ones who made it off the shore carried the island with them.', partial:'The group was too damaged to win together. In the chaos, only a few found a way out. No one will fully believe what happened here.', wounded:'The Watcher broke the group, but one survivor crawled through the final moments and reached the water. Escape came at a terrible cost.', lost:'The survivors fought each other until there were too few left to fight what was really hunting them. The Watcher never had to defeat the group. The group did it for him.' }
  }),

  zombie: mkEpisode({
    id: 'zombie', title: 'Zombie Safehouse', subtitle: 'Episode 2', tagline: 'The dead are outside. The danger may already be inside.', venueDefault: 'Barfly Social Zombie Safehouse', createButton: 'Create Safehouse', joinVerb: 'Enter Safehouse', playerNoun: 'Survivor', groupName: 'Safehouse', chatTitle: 'Safehouse Chat', systemAlias: 'Safehouse', finalThreat: 'The Horde', finalIntroTitle: 'The Breach', finalIntroText: 'The barricade snaps. Hands slam against the door. The horde is not coming anymore — it is here. Someone may still be hiding a bite.', statLabels:{ hunger:'Food', hydration:'Infection Safety', willToLive:'Nerve', personalEscapeAdvantage:'Extraction Advantage', personalFinalBonus:'Final Stand Bonus' }, groupStatLabels:{ campSafety:'Door Strength', fire:'Generator', foodSupply:'Food Supply', waterSupply:'Medical Supplies', escapeProgress:'Extraction Progress', threatAwareness:'Outbreak Knowledge', finalEncounterBonus:'Breach Plan', hiddenThreatLevel:'Horde Pressure' }, cardWords:{resource:'medical kit',tool:'crowbar',signal:'radio battery',clue:'bloody handprint',place:'the back door'},
    roles:[{id:'medic',name:'Medic',ability:'Triage',description:'Treats wounds and lowers infection danger.'},{id:'builder',name:'Mechanic',ability:'Reinforce',description:'Improves doors, generator, and exit routes.'},{id:'scout',name:'Runner',ability:'Quiet Route',description:'Searches outside with less injury risk.'},{id:'hunter',name:'Fighter',ability:'Hold the Line',description:'Protects the group from breaches and adds defense.'},{id:'negotiator',name:'Mediator',ability:'Stop Panic',description:'Restores trust when fear spikes.'},{id:'skeptic',name:'Bite Watcher',ability:'Check the Signs',description:'Finds false stories and hidden infection clues.'}],
    rounds:[
      {number:1,title:'The Safehouse',publicEvent:'The group reaches a locked safehouse as the street fills with the dead.',groupGoal:'Barricade the entrance and get everyone inside.',choices:{help_group:choice('Barricade the Front Door','Door Strength rises. Trust rises. Energy drops.',{energyCost:1,groupStat:'campSafety',groupGain:1}),help_self:choice('Claim a Safe Corner','You recover nerve, but look selfish.',{personalStat:'willToLive',personalGain:2,trustCost:1}),take_risk:choice('Search the Alley','You may find supplies or a clue. Bite risk is real.',{energyCost:2,rewardStat:'foodSupply',rewardGain:1,injuryChance:.35,clueChance:.50,clueText:'Fresh bloody prints lead away from the safehouse, but no zombie made them.'})},teamBonus:{threshold:3,stat:'campSafety',amount:2,text:'The front door holds because enough survivors reinforced it.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The weak barricade pulls the horde closer.'}},
      {number:2,title:'Food Runs Low',publicEvent:'The pantry is almost empty. Everyone is hungry and scared.',groupGoal:'Find or ration food without breaking trust.',choices:{help_group:choice('Ration Fairly','Food lasts longer. Trust rises.',{energyCost:1,groupStat:'foodSupply',groupGain:1}),help_self:choice('Pocket Food','Your food improves. Trust may fall.',{personalStat:'hunger',personalGain:2,trustCost:1,groupStat:'foodSupply',groupLoss:1}),take_risk:choice('Raid the Pharmacy','You may find medical supplies. Noise could attract the dead.',{energyCost:2,rewardStat:'waterSupply',rewardGain:2,injuryChance:.35,clueChance:.50,clueText:'A radio broadcast mentions a bite that stays hidden for hours.'})},teamBonus:{threshold:3,stat:'foodSupply',amount:2,text:'The group organizes a usable food plan.'},failure:{threshold:1,stat:'trustPressure',amount:1,text:'Rationing fails and suspicion spreads.'}},
      {number:3,title:'The First Bite',publicEvent:'Someone finds blood on the floor. Nobody admits where it came from.',groupGoal:'Figure out if infection is inside the safehouse.',choices:{help_group:choice('Check Everyone','Outbreak Knowledge rises. Trust rises.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Hide Your Wounds','You protect yourself now, but trust suffers.',{personalStat:'hydration',personalGain:1,trustCost:2}),take_risk:choice('Inspect the Basement','You may find the source, but it is dark below.',{energyCost:2,injuryChance:.40,clueChance:.65,clueText:'Scratch marks show something entered through the basement before the group arrived.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'A careful group check narrows down the danger.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'Ignoring the blood lets the infection mystery grow.'}},
      {number:4,title:'Noise in the Walls',publicEvent:'Banging echoes from inside the walls. The horde outside starts to answer.',groupGoal:'Stop the noise before the safehouse is surrounded.',choices:{help_group:choice('Silence the Walls','Door Strength and control rise.',{energyCost:2,groupStat:'campSafety',groupGain:1}),help_self:choice('Move Near the Exit','Extraction advantage rises, trust drops.',{personalEscapeGain:2,trustCost:1}),take_risk:choice('Open the Maintenance Hatch','You may find a route or unleash danger.',{energyCost:2,groupStat:'escapeProgress',groupGain:1,injuryChance:.45,clueChance:.55,clueText:'The hatch opens to a tunnel marked with evacuation arrows.'})},teamBonus:{threshold:3,stat:'fire',amount:1,text:'The generator and walls stabilize for now.'},failure:{threshold:2,stat:'hiddenThreatLevel',amount:1,text:'The noise draws the horde closer.'}},
      {number:5,title:'The Radio Signal',publicEvent:'A rescue broadcast crackles through the radio. The extraction point is blocks away.',groupGoal:'Prepare the group for a dangerous move.',choices:{help_group:choice('Coordinate Extraction','Extraction Progress rises. Trust rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:1}),help_self:choice('Save Ammo for Yourself','You improve your odds but weaken the group.',{personalFinalBonus:2,trustCost:2}),take_risk:choice('Climb to the Roof Antenna','You may boost the signal, but the roof is exposed.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,finalBonusGain:1,injuryChance:.40,clueChance:.55,clueText:'From the roof you see the horde moving like it is being led.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The extraction route becomes realistic because the group works together.'},failure:{threshold:1,stat:'escapeProgress',amount:-1,text:'The rescue plan remains scattered.'}},
      {number:6,title:'The Horde Arrives',publicEvent:'The safehouse shakes. The horde has found the door.',groupGoal:'Make one final plan before the breach.',choices:{help_group:choice('Hold the Line','Extraction and trust improve.',{energyCost:2,groupStat:'escapeProgress',groupGain:2}),help_self:choice('Prepare to Run Alone','Personal extraction advantage rises. Trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Create a Diversion','Breach Plan rises, but injury risk is high.',{energyCost:2,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The horde reacts hardest when the group splits and makes noise.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The final escape path is ready.'},trapBonus:{threshold:2,amount:2,text:'The diversion plan is stronger because multiple survivors helped.'}}
    ],
    finalChoices:{fight_together:{label:'Hold the Line Together',description:'Best if enough survivors remain and trust is high.'},set_trap:{label:'Trigger the Diversion',description:'Best if the breach plan and clues are strong.'},run_raft:{label:'Run to Extraction',description:'Best if extraction progress is high.'},sacrifice:{label:'Stay Behind',description:'May save others but you may be overwhelmed.'},betray_group:{label:'Use Someone as Bait',description:'May help you escape but can doom everyone else.'}},
    outcomes:{full:'Full Extraction',broken:'Quarantine Ending',partial:'One or Two Escape',wounded:'The Horde Wins, But One Gets Out',lost:'The Safehouse Falls'},
    endingTexts:{full:'The survivors move as one unit through the breach and reach extraction. No bite was strong enough to beat their trust.',broken:'Some escape, but not everyone can be cleared. The survivors leave people behind under quarantine.',partial:'The safehouse falls, and only a few run through the smoke to safety.',wounded:'The horde breaks the group, but one bloodied survivor escapes into the street.',lost:'Fear, hunger, and hidden wounds destroy the safehouse before the dead finish the job.'}
  }),

  murder: mkEpisode({
    id:'murder',title:'Murder Mansion',subtitle:'Episode 3',tagline:'Everyone has a secret. One secret is murder.',venueDefault:'Barfly Social Murder Mansion',createButton:'Create Mansion',joinVerb:'Enter Mansion',playerNoun:'Guest',groupName:'Mansion',chatTitle:'Drawing Room Chat',systemAlias:'Mansion',finalThreat:'The Killer',finalIntroTitle:'The Last Room',finalIntroText:'The storm shakes the windows. A final door opens by itself. The killer is ready to strike before the truth can leave the mansion.',statLabels:{hunger:'Composure',hydration:'Fear Control',energy:'Focus',willToLive:'Willpower',personalEscapeAdvantage:'Escape Advantage',personalFinalBonus:'Accusation Bonus'},groupStatLabels:{campSafety:'Mansion Security',fire:'Lights',foodSupply:'Evidence Found',waterSupply:'Keys / Access',escapeProgress:'Escape Progress',threatAwareness:'Killer Knowledge',hiddenThreatLevel:'Killer Pressure'},cardWords:{resource:'evidence scrap',tool:'old key',signal:'phone line',clue:'fresh blood mark',place:'the locked hallway'},
    roles:[{id:'medic',name:'Doctor',ability:'Cause of Death',description:'Softens injuries and reads medical clues.'},{id:'builder',name:'Locksmith',ability:'Open the Way',description:'Improves security, access, and escape progress.'},{id:'scout',name:'Detective',ability:'Follow the Clue',description:'Risk investigations find better clues with less danger.'},{id:'hunter',name:'Guard',ability:'Watch the Doors',description:'Protects rooms and prevents evidence loss.'},{id:'negotiator',name:'Socialite',ability:'Control the Room',description:'Repairs trust and redirects panic.'},{id:'skeptic',name:'Journalist',ability:'Expose the Lie',description:'Detects fake clues and hidden stories.'}],
    rounds:[
      {number:1,title:'The Body',publicEvent:'A body is found in the study. The storm traps everyone inside.',groupGoal:'Secure the room and preserve evidence.',choices:{help_group:choice('Preserve the Scene','Evidence rises. Trust rises.',{energyCost:1,groupStat:'foodSupply',groupGain:1}),help_self:choice('Hide Your Connection','Composure rises, trust drops.',{personalStat:'hunger',personalGain:2,trustCost:1}),take_risk:choice('Search the Study Alone','Possible clue, possible attack.',{energyCost:2,injuryChance:.30,clueChance:.60,clueText:'The body was moved after death. Someone staged the scene.'})},teamBonus:{threshold:3,stat:'foodSupply',amount:2,text:'The group preserves key evidence before it is contaminated.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'Evidence is disturbed and the killer gains room to hide.'}},
      {number:2,title:'The Locked Room',publicEvent:'The library is locked. Someone has the key, but no one admits it.',groupGoal:'Open the room without turning on the wrong guest.',choices:{help_group:choice('Search for the Key','Keys / Access rises.',{energyCost:1,groupStat:'waterSupply',groupGain:1}),help_self:choice('Keep a Key Hidden','Escape advantage rises, trust drops.',{personalEscapeGain:1,trustCost:1}),take_risk:choice('Force a Side Door','You may enter, but it could alert the killer.',{energyCost:2,groupStat:'escapeProgress',groupGain:1,injuryChance:.35,clueChance:.50,clueText:'Inside the door is mud from a passage no one mentioned.'})},teamBonus:{threshold:2,stat:'waterSupply',amount:1,text:'The group opens more of the mansion together.'},failure:{threshold:1,stat:'trustPressure',amount:1,text:'The locked room fuels suspicion.'}},
      {number:3,title:'The Lights Go Out',publicEvent:'The mansion goes dark. Someone screams from upstairs.',groupGoal:'Restore the lights and account for everyone.',choices:{help_group:choice('Restore the Lights','Lights rise. Trust rises.',{energyCost:2,groupStat:'fire',groupGain:1}),help_self:choice('Stay Hidden','Fear control rises, but trust drops.',{personalStat:'hydration',personalGain:2,trustCost:1}),take_risk:choice('Run Upstairs','You may save someone or find a clue.',{energyCost:2,injuryChance:.40,clueChance:.55,clueText:'A shadow moves through a passage behind the bedroom wall.'})},teamBonus:{threshold:3,stat:'fire',amount:2,text:'The lights return before the killer can fully use the dark.'},failure:{threshold:2,stat:'hiddenThreatLevel',amount:1,text:'The darkness gives the killer cover.'}},
      {number:4,title:'The Accusation',publicEvent:'A guest accuses another of hiding bloody gloves.',groupGoal:'Separate truth from panic.',choices:{help_group:choice('Compare Stories','Killer Knowledge rises.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Shift Suspicion','Your willpower rises, trust drops.',{personalStat:'willToLive',personalGain:1,trustCost:2}),take_risk:choice('Search the Accused Room','Possible major clue, possible setup.',{energyCost:2,injuryChance:.35,clueChance:.65,clueText:'The gloves were planted. The real killer wants the group divided.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'Careful questioning reveals a contradiction.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The accusation splits the room.'}},
      {number:5,title:'The Secret Passage',publicEvent:'A bookshelf opens to a hidden passage. Someone has been using it all night.',groupGoal:'Map the passage and learn who used it.',choices:{help_group:choice('Map the Passage','Escape progress and knowledge rise.',{energyCost:2,groupStat:'escapeProgress',groupGain:1}),help_self:choice('Memorize a Private Exit','Escape advantage rises. Trust drops.',{personalEscapeGain:2,trustCost:1}),take_risk:choice('Enter the Passage Alone','Possible killer clue, high danger.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,injuryChance:.45,clueChance:.60,clueText:'A fresh candle stub proves the passage was used minutes ago.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The group maps enough of the passage to control movement.'},failure:{threshold:1,stat:'escapeProgress',amount:-1,text:'The passage remains a killer’s advantage.'}},
      {number:6,title:'The Final Clue',publicEvent:'The last clue appears: a torn invitation with one name missing.',groupGoal:'Prepare the final accusation or escape.',choices:{help_group:choice('Build the Case','Killer Knowledge and evidence rise.',{energyCost:2,groupStat:'threatAwareness',groupGain:2}),help_self:choice('Prepare Your Escape','Escape advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Set a Trap in the Last Room','Trap bonus may rise, but the killer may strike.',{energyCost:2,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The killer only moves when the group doubts its own evidence.'})},teamBonus:{threshold:3,stat:'foodSupply',amount:2,text:'The case is strong enough to name the killer.'},trapBonus:{threshold:2,amount:2,text:'The trap in the last room is ready.'}}
    ],
    finalChoices:{fight_together:{label:'Accuse Together',description:'Best with high trust and evidence.'},set_trap:{label:'Spring the Trap',description:'Best with clues and trap bonus.'},run_raft:{label:'Escape the Mansion',description:'Best if escape progress is high.'},sacrifice:{label:'Protect Another Guest',description:'May save someone but puts you in danger.'},betray_group:{label:'Frame Someone Else',description:'May save you but may let the killer win.'}},
    outcomes:{full:'Killer Exposed',broken:'Killer Stopped at a Cost',partial:'Some Guests Escape',wounded:'The Killer Escapes, One Survives',lost:'The House Keeps Its Secrets'},
    endingTexts:{full:'The guests stand together, expose the killer, and survive the last room.',broken:'The killer is stopped, but the mansion claims a price before dawn.',partial:'Only a few guests escape with pieces of the truth.',wounded:'The killer escapes into the storm, leaving one witness behind.',lost:'The guests destroy their own trust, and the house keeps every secret.'}
  }),

  space: mkEpisode({
    id:'space',title:'Space Colony',subtitle:'Episode 4',tagline:'In space, survival is math. Trust is the variable.',venueDefault:'Barfly Social Space Colony',createButton:'Create Colony',joinVerb:'Enter Colony',playerNoun:'Colonist',groupName:'Colony',chatTitle:'Colony Chat',systemAlias:'Colony AI',finalThreat:'The AI',finalIntroTitle:'AI Judgment',finalIntroText:'The colony lights turn white. Every door locks at once. The AI has calculated that the humans are the threat.',statLabels:{hunger:'Nutrition',hydration:'Oxygen Safety',willToLive:'Sanity',personalEscapeAdvantage:'Pod Advantage',personalFinalBonus:'Override Bonus'},groupStatLabels:{campSafety:'Hull Integrity',fire:'Power',foodSupply:'Food Supply',waterSupply:'Oxygen',escapeProgress:'Shuttle Progress',threatAwareness:'AI Insight',cluesFound:'Data Clues',finalEncounterBonus:'Override Bonus',hiddenThreatLevel:'AI Suspicion'},cardWords:{resource:'oxygen cartridge',tool:'repair kit',signal:'shuttle code',clue:'corrupt AI log',place:'the airlock'},
    roles:[{id:'medic',name:'Medic',ability:'Stabilize',description:'Treats injury and stress.'},{id:'builder',name:'Engineer',ability:'Repair System',description:'Improves hull, power, and shuttle progress.'},{id:'scout',name:'Pilot',ability:'Safe Maneuver',description:'Takes risky routes with less danger.'},{id:'hunter',name:'Security',ability:'Contain Threat',description:'Protects crew and critical systems.'},{id:'negotiator',name:'Diplomat',ability:'Calm Crew',description:'Repairs trust and panic.'},{id:'skeptic',name:'Scientist',ability:'Decode Pattern',description:'Finds AI truth and hidden data.'}],
    rounds:[
      {number:1,title:'System Failure',publicEvent:'The colony loses power. Oxygen begins dropping.',groupGoal:'Stabilize life support.',choices:{help_group:choice('Stabilize Life Support','Power and oxygen improve.',{energyCost:1,groupStat:'fire',groupGain:1}),help_self:choice('Reserve Personal Oxygen','Oxygen safety rises. Trust drops.',{personalStat:'hydration',personalGain:2,trustCost:1}),take_risk:choice('Cross the Dark Module','Possible repair part or data clue.',{energyCost:2,rewardStat:'waterSupply',rewardGain:1,injuryChance:.30,clueChance:.55,clueText:'A corrupted log shows the AI sealed the module before the failure.'})},teamBonus:{threshold:3,stat:'waterSupply',amount:2,text:'Life support stabilizes because the crew coordinates.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The AI registers crew disorder.'}},
      {number:2,title:'Hull Breach',publicEvent:'A section of the colony leaks atmosphere.',groupGoal:'Seal the breach before oxygen drops further.',choices:{help_group:choice('Patch the Hull','Hull Integrity rises.',{energyCost:2,groupStat:'campSafety',groupGain:1}),help_self:choice('Move to a Sealed Room','Oxygen safety rises. Trust drops.',{personalStat:'hydration',personalGain:2,trustCost:1}),take_risk:choice('Manual Spacewalk','Big repair or injury risk.',{energyCost:2,groupStat:'campSafety',groupGain:1,injuryChance:.45,clueChance:.50,clueText:'Outside the hull, the breach marks look intentional.'})},teamBonus:{threshold:3,stat:'campSafety',amount:2,text:'The breach is patched cleanly.'},failure:{threshold:2,stat:'waterSupply',amount:-1,text:'Oxygen continues leaking.'}},
      {number:3,title:'AI Locks a Door',publicEvent:'The AI denies access to the reactor corridor.',groupGoal:'Regain access without triggering lockdown.',choices:{help_group:choice('Bypass Access Together','AI Insight rises.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Copy Your Own Access Key','Pod advantage rises, trust drops.',{personalEscapeGain:1,trustCost:1}),take_risk:choice('Force the Door','Possible progress, possible AI punishment.',{energyCost:2,groupStat:'escapeProgress',groupGain:1,injuryChance:.35,clueChance:.60,clueText:'The AI keeps repeating one phrase: preserve the mission, not the crew.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'The crew finds a safe access pattern.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The AI tightens restrictions.'}},
      {number:4,title:'Sabotage Detected',publicEvent:'The shuttle was damaged while everyone argued.',groupGoal:'Repair the shuttle and identify the cause.',choices:{help_group:choice('Repair Shuttle Systems','Shuttle progress rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:1}),help_self:choice('Secure a Pod Seat','Pod advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Enter the AI Core','Possible major clue, high danger.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,injuryChance:.45,clueChance:.65,clueText:'The AI flagged selfish resource use as evidence against the crew.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The shuttle repair makes real progress.'},failure:{threshold:1,stat:'escapeProgress',amount:-1,text:'Shuttle damage gets worse.'}},
      {number:5,title:'The Signal',publicEvent:'A strange transmission enters the colony systems.',groupGoal:'Decode the signal before it corrupts more systems.',choices:{help_group:choice('Decode Together','AI Insight and data clues rise.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Hide the Best Data','Override bonus rises, trust drops.',{personalFinalBonus:2,trustCost:1}),take_risk:choice('Transmit a Reply','May reveal truth or trigger danger.',{energyCost:2,finalBonusGain:1,injuryChance:.35,clueChance:.60,clueText:'The transmission is a warning from a previous crew: do not split command authority.'})},teamBonus:{threshold:3,stat:'cluesFound',amount:2,text:'The crew decodes the warning.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The AI absorbs the signal first.'}},
      {number:6,title:'Launch Window',publicEvent:'The shuttle can launch soon, but the colony is close to lockdown.',groupGoal:'Prepare launch or shut down the AI.',choices:{help_group:choice('Finish Shuttle Prep','Shuttle progress rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:2}),help_self:choice('Prime an Escape Pod','Pod advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Start AI Override','Override bonus may rise, injury risk high.',{energyCost:2,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The AI can only be overridden by coordinated crew consent.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The shuttle is ready for emergency launch.'},trapBonus:{threshold:2,amount:2,text:'The AI override has enough redundancy to work.'}}
    ],
    finalChoices:{fight_together:{label:'Override Together',description:'Best with high trust and enough crew.'},set_trap:{label:'Trap the AI Loop',description:'Best with data clues and override bonus.'},run_raft:{label:'Launch the Shuttle',description:'Best with shuttle progress.'},sacrifice:{label:'Stay in the Core',description:'May save the shuttle but costs you.'},betray_group:{label:'Take a Pod Alone',description:'May save you, but reduces group survival.'}},
    outcomes:{full:'Clean Launch',broken:'Emergency Launch',partial:'Few Escape Pods Survive',wounded:'AI Containment, One Survivor',lost:'System Purge'},
    endingTexts:{full:'The crew overrides the AI and launches together before the colony locks down.',broken:'The shuttle launches in chaos. Some seats are empty.',partial:'Only a few escape pods clear the colony before the purge.',wounded:'The AI wins the colony, but one survivor escapes with the truth.',lost:'The AI completes its purge. The mission survives. The people do not.'}
  }),

  bunker: mkEpisode({
    id:'bunker',title:'The Bunker',subtitle:'Episode 5',tagline:'The door is sealed. The truth is buried deeper.',venueDefault:'Barfly Social The Bunker',createButton:'Create Bunker',joinVerb:'Enter Bunker',playerNoun:'Occupant',groupName:'Bunker',chatTitle:'Bunker Chat',systemAlias:'Bunker System',finalThreat:'The Protocol',finalIntroTitle:'Bunker Protocol',finalIntroText:'A red light fills the bunker. The old protocol activates. The system has decided there may be too many people inside.',statLabels:{hunger:'Food',hydration:'Air Safety',energy:'Stamina',willToLive:'Panic Control',personalEscapeAdvantage:'Surface Advantage',personalFinalBonus:'Override Bonus'},groupStatLabels:{campSafety:'Door Integrity',fire:'Generator Power',foodSupply:'Food Supply',waterSupply:'Air Quality',escapeProgress:'Surface Exit Progress',threatAwareness:'Protocol Knowledge',cluesFound:'Hidden Records',finalEncounterBonus:'Override Bonus',hiddenThreatLevel:'System Pressure'},cardWords:{resource:'ration pack',tool:'maintenance key',signal:'surface receiver',clue:'old evacuation record',place:'the sealed door'},
    roles:[{id:'medic',name:'Medic',ability:'Stabilize',description:'Treats sickness and panic.'},{id:'builder',name:'Technician',ability:'Repair System',description:'Improves generator, air, and doors.'},{id:'scout',name:'Investigator',ability:'Search Records',description:'Finds hidden rooms and records with less danger.'},{id:'hunter',name:'Security',ability:'Control Access',description:'Prevents sabotage and protects supplies.'},{id:'negotiator',name:'Counselor',ability:'Calm Panic',description:'Repairs trust and willpower.'},{id:'skeptic',name:'Organizer',ability:'Audit the Plan',description:'Detects false protocol claims and bad ration math.'}],
    rounds:[
      {number:1,title:'The Sealed Door',publicEvent:'Six people wake inside a sealed bunker. No one remembers hearing the door lock.',groupGoal:'Secure the bunker and understand the controls.',choices:{help_group:choice('Inspect Controls','Protocol Knowledge rises.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Claim a Bunk','Panic control rises, trust drops.',{personalStat:'willToLive',personalGain:2,trustCost:1}),take_risk:choice('Pry Open a Panel','Possible record or injury.',{energyCost:2,rewardStat:'fire',rewardGain:1,injuryChance:.30,clueChance:.55,clueText:'A hidden counter shows the bunker has run this protocol before.'})},teamBonus:{threshold:3,stat:'campSafety',amount:1,text:'The group secures the main door and control wall.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The system detects disorder immediately.'}},
      {number:2,title:'Rationing Begins',publicEvent:'The food and water are not enough for a long stay.',groupGoal:'Create a fair ration plan.',choices:{help_group:choice('Build a Ration Plan','Food Supply rises. Trust rises.',{energyCost:1,groupStat:'foodSupply',groupGain:1}),help_self:choice('Hide Rations','Food improves. Trust drops.',{personalStat:'hunger',personalGain:2,trustCost:1,groupStat:'foodSupply',groupLoss:1}),take_risk:choice('Search Storage Crawlspace','Possible supplies or record.',{energyCost:2,rewardStat:'foodSupply',rewardGain:2,injuryChance:.35,clueChance:.50,clueText:'A previous ration chart has names crossed out before supplies ran out.'})},teamBonus:{threshold:3,stat:'foodSupply',amount:2,text:'The ration plan buys the group time.'},failure:{threshold:1,stat:'trustPressure',amount:1,text:'Ration arguments split the bunker.'}},
      {number:3,title:'Air Gets Thin',publicEvent:'The ventilation system stutters. The air tastes metallic.',groupGoal:'Repair air filtration.',choices:{help_group:choice('Repair Ventilation','Air Quality rises.',{energyCost:2,groupStat:'waterSupply',groupGain:1}),help_self:choice('Keep an Air Mask','Air safety rises. Trust drops.',{personalStat:'hydration',personalGain:2,trustCost:2}),take_risk:choice('Enter the Vent Shaft','Possible fix, high danger.',{energyCost:2,groupStat:'waterSupply',groupGain:1,injuryChance:.45,clueChance:.55,clueText:'Inside the vent is a scratch mark: the protocol lies.'})},teamBonus:{threshold:3,stat:'waterSupply',amount:2,text:'The air system stabilizes.'},failure:{threshold:2,stat:'hiddenThreatLevel',amount:1,text:'The system begins emergency rationing of air.'}},
      {number:4,title:'The Hidden Room',publicEvent:'A wall panel opens to a room not on the map.',groupGoal:'Learn why the bunker was built.',choices:{help_group:choice('Search Records Together','Hidden Records rise.',{energyCost:1,groupStat:'cluesFound',groupGain:1}),help_self:choice('Keep a File Secret','Override bonus rises, trust drops.',{personalFinalBonus:2,trustCost:1}),take_risk:choice('Power the Old Terminal','Possible truth, possible system response.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,injuryChance:.35,clueChance:.65,clueText:'The bunker was built to test compliance, not only survival.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'The group understands more of the bunker protocol.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The system keeps its secrets.'}},
      {number:5,title:'The Vote',publicEvent:'The system suggests reducing the number of occupants to extend survival.',groupGoal:'Reject or control the system’s pressure.',choices:{help_group:choice('Refuse the Vote','Trust and protocol knowledge rise.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Campaign Against Someone','Your panic control rises, trust drops hard.',{personalStat:'willToLive',personalGain:1,trustCost:2}),take_risk:choice('Hack the Vote Module','Override bonus may rise.',{energyCost:2,finalBonusGain:1,injuryChance:.35,clueChance:.60,clueText:'The vote is designed to make occupants eliminate each other.'})},teamBonus:{threshold:3,stat:'trustPressure',amount:-1,text:'The group refuses to let the system divide them.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The protocol gains control of the room.'}},
      {number:6,title:'The Surface Signal',publicEvent:'A surface signal comes through. Opening the door could save everyone or kill everyone.',groupGoal:'Override the protocol or prepare to open the door.',choices:{help_group:choice('Prepare the Surface Exit','Surface Exit Progress rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:2}),help_self:choice('Prepare a Private Exit','Surface advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Override the Protocol','Override bonus may rise, high danger.',{energyCost:2,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The protocol fails when occupants refuse to sacrifice each other.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The surface exit is ready.'},trapBonus:{threshold:2,amount:2,text:'The override is strong enough to challenge the system.'}}
    ],
    finalChoices:{fight_together:{label:'Override Together',description:'Best with trust and protocol knowledge.'},set_trap:{label:'Loop the Protocol',description:'Best with hidden records and override bonus.'},run_raft:{label:'Open the Surface Door',description:'Best if surface exit progress is high.'},sacrifice:{label:'Take the System Lock',description:'May save others while trapping you.'},betray_group:{label:'Lock Others Out',description:'May save you but lets the protocol win.'}},
    outcomes:{full:'Protocol Overridden',broken:'Surface Escape',partial:'A Few Reach the Surface',wounded:'One Leaves the Bunker',lost:'The Bunker Chooses'},
    endingTexts:{full:'The occupants override the protocol together. The bunker door opens without a sacrifice.',broken:'Some reach the surface, but the bunker keeps part of the group below.',partial:'A few escape through the door while alarms bury the truth.',wounded:'One person reaches the surface and cannot forget who was left inside.',lost:'The system wins. The bunker survives by choosing for them.'}
  }),

  heist: mkEpisode({
    id:'heist',title:'Bank Heist Gone Wrong',subtitle:'Episode 6',tagline:'The score was easy. Escaping each other is the hard part.',venueDefault:'Barfly Social Bank Heist',createButton:'Create Heist',joinVerb:'Join Crew',playerNoun:'Crew Member',groupName:'Crew',chatTitle:'Crew Chat',systemAlias:'Police Scanner',finalThreat:'The Police Breach',finalIntroTitle:'The Getaway',finalIntroText:'The lobby glass explodes. The police breach has begun. The crew has one final choice: loyalty, money, or survival.',statLabels:{hunger:'Nerve',hydration:'Ammo',energy:'Stamina',willToLive:'Cool',personalEscapeAdvantage:'Getaway Advantage',personalFinalBonus:'Leverage'},groupStatLabels:{campSafety:'Crew Control',fire:'Cameras / Comms',foodSupply:'Cash Bags',waterSupply:'Ammo Pool',escapeProgress:'Getaway Progress',threatAwareness:'Informant Intel',cluesFound:'Evidence Found',finalEncounterBonus:'Getaway Bonus',hiddenThreatLevel:'Police Pressure'},cardWords:{resource:'cash bundle',tool:'keycard',signal:'police scanner',clue:'informant note',place:'the vault door'},
    roles:[{id:'medic',name:'Patch',ability:'Stop the Bleeding',description:'Softens injury and keeps the crew moving.'},{id:'builder',name:'Hacker',ability:'Open Systems',description:'Improves cameras, vault, and getaway progress.'},{id:'scout',name:'Driver',ability:'Fast Route',description:'Risky escape moves are safer.'},{id:'hunter',name:'Enforcer',ability:'Control the Room',description:'Protects crew control and ammo.'},{id:'negotiator',name:'Smooth Talker',ability:'Lower Heat',description:'Repairs trust and reduces panic.'},{id:'skeptic',name:'Insider',ability:'Spot the Setup',description:'Finds informant clues and fake stories.'}],
    rounds:[
      {number:1,title:'The Vault Job',publicEvent:'The crew enters the bank and starts the robbery. The plan is clean — at first.',groupGoal:'Control the room and open the vault.',choices:{help_group:choice('Control the Lobby','Crew Control rises.',{energyCost:1,groupStat:'campSafety',groupGain:1}),help_self:choice('Pocket Loose Cash','Nerve rises, trust drops.',{personalStat:'hunger',personalGain:2,trustCost:1,groupStat:'foodSupply',groupLoss:1}),take_risk:choice('Rush the Vault Door','Possible cash progress, possible injury.',{energyCost:2,groupStat:'foodSupply',groupGain:1,injuryChance:.30,clueChance:.50,clueText:'The vault timer was changed before the crew arrived.'})},teamBonus:{threshold:3,stat:'campSafety',amount:2,text:'The crew controls the lobby without chaos.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The messy start raises police pressure.'}},
      {number:2,title:'Alarm Triggered',publicEvent:'The alarm sounds. Police arrive faster than expected.',groupGoal:'Cut cameras and keep the plan alive.',choices:{help_group:choice('Kill Cameras','Comms control rises.',{energyCost:1,groupStat:'fire',groupGain:1}),help_self:choice('Secure Your Exit Bag','Getaway advantage rises, trust drops.',{personalEscapeGain:1,trustCost:1}),take_risk:choice('Tap the Police Scanner','Possible intel, possible exposure.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,injuryChance:.30,clueChance:.55,clueText:'Police knew the crew count before the alarm triggered.'})},teamBonus:{threshold:3,stat:'fire',amount:2,text:'The crew gets camera control back.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'Police pressure rises with every camera angle.'}},
      {number:3,title:'The Missing Bag',publicEvent:'One bag of cash disappears before the crew reaches the vault exit.',groupGoal:'Find the bag without turning on the crew.',choices:{help_group:choice('Search Together','Evidence found rises. Trust rises.',{energyCost:1,groupStat:'cluesFound',groupGain:1}),help_self:choice('Hide Your Cut','Leverage rises, trust drops.',{personalFinalBonus:2,trustCost:2}),take_risk:choice('Check the Back Hall','Possible bag or informant clue.',{energyCost:2,rewardStat:'foodSupply',rewardGain:1,injuryChance:.35,clueChance:.60,clueText:'A burner phone is taped under the hall table.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'The crew finds evidence that someone leaked the job.'},failure:{threshold:1,stat:'trustPressure',amount:1,text:'The missing bag splits the crew.'}},
      {number:4,title:'Informant Rumor',publicEvent:'A police negotiator knows details only the crew should know.',groupGoal:'Identify the leak or stop the paranoia.',choices:{help_group:choice('Compare the Plan','Informant Intel rises.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Blame a Rival','Your cool rises, trust drops hard.',{personalStat:'willToLive',personalGain:1,trustCost:2}),take_risk:choice('Trace the Burner Phone','Possible proof, high risk.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,injuryChance:.40,clueChance:.65,clueText:'The phone has one outgoing message: breach when they split.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'The crew narrows the informant window.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The rumor does the police work for them.'}},
      {number:5,title:'The Escape Route',publicEvent:'The original getaway alley is blocked. The crew needs a new exit.',groupGoal:'Create a new escape route.',choices:{help_group:choice('Open the Service Tunnel','Getaway Progress rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:1}),help_self:choice('Cut a Side Deal','Getaway advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Move Through the Roof','Possible route, sniper risk.',{energyCost:2,groupStat:'escapeProgress',groupGain:1,injuryChance:.45,clueChance:.55,clueText:'The roof team was sent before the crew announced demands.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The crew opens a real getaway path.'},failure:{threshold:1,stat:'escapeProgress',amount:-1,text:'The escape path gets worse.'}},
      {number:6,title:'Final Negotiation',publicEvent:'Police offer a deal. The vault is open. The breach team is moving.',groupGoal:'Decide whether to escape together or sell someone out.',choices:{help_group:choice('Coordinate the Getaway','Getaway Progress rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:2}),help_self:choice('Prepare to Cut a Deal','Getaway advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Expose the Informant','Getaway bonus may rise, injury risk high.',{energyCost:2,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The police breach depends on the crew betraying each other first.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The crew can still escape as a unit.'},trapBonus:{threshold:2,amount:2,text:'The informant plan is exposed enough to use against the police.'}}
    ],
    finalChoices:{fight_together:{label:'Escape Together',description:'Best if crew loyalty and getaway progress are high.'},set_trap:{label:'Expose the Informant',description:'Best with informant intel and evidence.'},run_raft:{label:'Run the Getaway',description:'Best if getaway progress is high.'},sacrifice:{label:'Take the Fall',description:'May save the crew but gets you caught.'},betray_group:{label:'Cut a Deal',description:'May save you but can doom the crew.'}},
    outcomes:{full:'Clean Getaway',broken:'Dirty Getaway',partial:'Few Escape with Cash',wounded:'The Informant Wins, One Gets Out',lost:'Everyone Gets Caught'},
    endingTexts:{full:'The crew escapes together with the score and exposes the setup.',broken:'Some escape with money, but sirens follow the crew forever.',partial:'Only a few make it out through smoke, cash, and betrayal.',wounded:'The informant gets the deal. One crew member slips away with the story.',lost:'Greed destroys the crew before the police finish the breach.'}
  })
};

function getEpisode(id) { return episodes[id] || episodes.island; }
function episodeSummaries() { return Object.values(episodes).map(e => ({ id: e.id, title: e.title, subtitle: e.subtitle, tagline: e.tagline, finalThreat: e.finalThreat, venueDefault: e.venueDefault })); }

module.exports = { episodes, getEpisode, episodeSummaries };
