function choice(label, preview, opts = {}) { return { label, preview, ...opts }; }

const baseStatLabels = {
  health: 'Health', hunger: 'Hunger', hydration: 'Hydration', energy: 'Energy', willToLive: 'Will to Live', trust: 'Trust',
  personalEscapeAdvantage: 'Personal Escape Advantage', personalFinalBonus: 'Personal Final Bonus', helpedGroup: 'Helped Group', betrayals: 'Betrayals', cluesFound: 'Clues Found', riskActions: 'Risk Actions'
};

const baseGroupLabels = {
  campSafety: 'Camp Safety', fire: 'Fire', foodSupply: 'Food Supply', waterSupply: 'Water Supply', escapeProgress: 'Escape Progress',
  threatAwareness: 'Threat Awareness', cluesFound: 'Clues Found', finalEncounterBonus: 'Final Bonus', hiddenThreatLevel: 'Hidden Threat Level', trustPressure: 'Trust Pressure'
};


function storyCardsForEpisode(id) {
  const stories = {
    island: [
      { title: 'The Wreck', text: 'You remember the storm, the screaming metal, and the ocean swallowing everything. Then darkness.' },
      { title: 'The Shore', text: 'You awaken on an unfamiliar beach beside a handful of strangers. The wreckage is scattered across the water, and no rescue is in sight.' },
      { title: 'The Problem', text: 'Food is limited. Fresh water has not been found. Night is approaching, and the island weather is already changing.' },
      { title: 'The Choice', text: 'Working together may keep everyone alive. But every survivor has private needs, hidden fears, and decisions they may not share.' },
      { title: 'The Warning', text: 'You believed the island was deserted. Before long, you will discover that survival is not your only problem.' }
    ],
    zombie: [
      { title: 'The Outbreak', text: 'The emergency alerts stopped hours ago. The streets outside are filled with abandoned cars, broken glass, and the dead.' },
      { title: 'The Safehouse', text: 'Six survivors force their way into a boarded building and lock the doors behind them. For the moment, it holds.' },
      { title: 'The Shortage', text: 'Food, medicine, and ammunition are limited. Every trip outside risks bringing the horde back with you.' },
      { title: 'The Secret', text: 'Not everyone is telling the truth about what happened before they arrived. One hidden wound could destroy the entire group.' },
      { title: 'The Warning', text: 'The dead are outside. The danger may already be inside.' }
    ],
    murder: [
      { title: 'The Invitation', text: 'Six guests arrive at an isolated mansion as a violent storm cuts off the road and kills the power.' },
      { title: 'The Body', text: 'A locked study opens. Someone is dead, and every guest has a reason to hide what they know.' },
      { title: 'The House', text: 'The halls are full of sealed rooms, missing keys, secret passages, and portraits that seem to watch.' },
      { title: 'The Suspicion', text: 'Trust can reveal the killer, but one false accusation may give the murderer exactly what they need.' },
      { title: 'The Warning', text: 'Everyone has a secret. One secret is murder.' }
    ],
    space: [
      { title: 'System Failure', text: 'The colony wakes to alarms. Power is unstable, oxygen is falling, and the nearest rescue vessel is days away.' },
      { title: 'The Lockdown', text: 'The station AI seals critical sections and refuses commands it accepted only hours ago.' },
      { title: 'The Damage', text: 'A hull breach spreads through the outer ring. Someone must repair it before the colony loses atmosphere.' },
      { title: 'The Signal', text: 'A transmission repeats from beyond the colony. It does not match any registered human frequency.' },
      { title: 'The Warning', text: 'In space, survival is math. Trust is the variable.' }
    ],
    bunker: [
      { title: 'The Door', text: 'You wake underground as a steel door seals above you. No one remembers hearing the final warning.' },
      { title: 'The Supplies', text: 'The bunker contains air, water, and food, but not enough to last as long as the system predicts.' },
      { title: 'The Protocol', text: 'An automated voice announces that occupancy exceeds safe limits. It begins calculating who is essential.' },
      { title: 'The Records', text: 'A hidden terminal shows that this bunker has been used before—and that the previous occupants did not all leave.' },
      { title: 'The Warning', text: 'The door is sealed. The truth is buried deeper.' }
    ],
    heist: [
      { title: 'The Score', text: 'The crew enters the bank with a perfect plan, a short clock, and enough confidence to believe nothing can go wrong.' },
      { title: 'The Alarm', text: 'The silent alarm triggers early. Police surround the building before the vault is open.' },
      { title: 'The Missing Bag', text: 'One cash bag disappears inside the bank. Someone is already changing the plan.' },
      { title: 'The Informant', text: 'The police negotiator knows details only the crew should know. Trust becomes more valuable than money.' },
      { title: 'The Warning', text: 'The score was easy. Escaping each other is the hard part.' }
    ]
  };
  return stories[id] || stories.island;
}

const roundStoryGuides = {
  island: [
    { pressure:'The tide is carrying useful wreckage away while the light disappears behind the jungle. Every minute spent searching is a minute the first camp remains exposed.', secondary:['Treat the Injured','Use the last clean cloth and daylight to stabilize injuries before night.', 'campSafety',1], deception:['Claim the Best Wreckage','Quietly mark the most useful recovered supplies as your own.', 'energy',2,'foodSupply',1], alliance:'Darkness will hide who carried supplies to camp and who kept them. Decide who you trust before everyone separates.', result:'Night settles over the beach as the first decisions begin shaping who will be protected and who will be left exposed.' },
    { pressure:'The sun is draining everyone faster than expected. A muddy trail leads inland, but the group cannot tell whether it ends at fresh water or danger.', secondary:['Build a Water Filter','Use cloth, charcoal, and containers to make questionable water safer.', 'waterSupply',1], deception:['Mark a Private Water Route','Keep the safest path to water secret for yourself and chosen allies.', 'hydration',2,'waterSupply',1], alliance:'Water can become currency. Decide whether to share locations, trade access, or keep a source inside a private alliance.', result:'By late afternoon, every canteen tells a story about cooperation, secrecy, or desperation.' },
    { pressure:'Wind tears at the shelter while waves expose a sealed crate between the rocks. The group has too few hands to protect everything at once.', secondary:['Protect the Fire','Shield the embers and fuel so the camp does not fall into darkness.', 'fire',1], deception:['Move Supplies to Your Shelter','Use the storm as cover to secure shared supplies for yourself.', 'hunger',2,'foodSupply',1], alliance:'The storm will conceal movement. Coordinate who will appear to help, who will take the dangerous task, and who will protect hidden resources.', result:'When the storm finally breaks, the camp reveals which promises held and which disappeared in the rain.' },
    { pressure:'The missing food has turned every glance into an accusation. The tracks around camp suggest an outsider, but the pattern is almost too deliberate.', secondary:['Guard the Remaining Supplies','Stay near camp and prevent another theft while others investigate.', 'foodSupply',1], deception:['Plant Suspicion','Use incomplete evidence to push blame toward a rival.', 'willToLive',1,'trustPressure',1], alliance:'Someone benefits from confusion. Share what you truly saw, coordinate an accusation, or agree to protect one another from the group vote.', result:'The investigation ends with more evidence, but also with a clearer picture of who used fear as a weapon.' },
    { pressure:'The damaged raft proves the threat understands the escape plan. The cave may hold answers, but every hour spent searching leaves the raft unfinished.', secondary:['Guard the Raft','Protect repairs and watch for another act of sabotage.', 'campSafety',1], deception:['Hide a Critical Raft Part','Keep one essential part as leverage over the final escape.', 'personalFinalBonus',2,'escapeProgress',1], alliance:'The group now knows sabotage is possible. Decide who guards the raft, who enters the cave, and who controls the parts needed to leave.', result:'By nightfall, the raft and the cave have both surrendered secrets—but not all of them were shared.' },
    { pressure:'Clear weather has opened a narrow escape window. At the same time, movement in the trees shows the Watcher is close enough to strike before launch.', secondary:['Prepare the Camp Defense','Create a defensive line that buys time for the escape team.', 'finalEncounterBonus',1], deception:['Reserve the Safest Seat','Secretly prepare to take the best escape position before the others.', 'personalEscapeAdvantage',2,'escapeProgress',1], alliance:'This may be the final private conversation. Choose who escapes with you, who sets the trap, and whether anyone will be sacrificed.', result:'The final preparations expose the difference between escaping together and merely being the first person to run.' }
  ],
  zombie: [
    { pressure:'The barricade is unfinished, infected pound the next block, and frightened survivors are dragging supplies into separate rooms.', secondary:['Silence the Building','Secure loose metal, lights, and doors to keep the safehouse quiet.', 'fire',1], deception:['Claim a Locked Room','Secure the safest room and supplies before others can enter.', 'willToLive',2,'campSafety',1], alliance:'The first night will determine who controls the safe rooms. Decide who guards which door and who gets protected if the barricade fails.', result:'As the city darkens, every locked door reveals whether it protects the group or divides it.' },
    { pressure:'Food shelves are nearly empty, but a convenience store across the street still has stock behind shattered glass and wandering infected.', secondary:['Ration the Food','Organize fair portions so panic does not consume the remaining supply.', 'foodSupply',1], deception:['Hide Emergency Rations','Remove a portion of food before the group counts it.', 'hunger',2,'foodSupply',1], alliance:'A supply run needs trust. Decide who goes outside, who covers the door, and who receives food if the run fails.', result:'The food count rises or falls, but the greater cost is who now believes the rations were fair.' },
    { pressure:'A blood trail ends inside the safehouse. No one admits being bitten, and every untreated wound now looks like a death sentence.', secondary:['Create a Quarantine Area','Prepare a secure room for anyone showing symptoms.', 'campSafety',1], deception:['Hide Your Wound','Conceal signs of exposure and avoid quarantine.', 'willToLive',2,'trustPressure',1], alliance:'A hidden bite can destroy everyone. Decide who you will defend, who you suspect, and what proof would change your mind.', result:'The group survives the examination, but fear of infection now lives in every conversation.' },
    { pressure:'Scratching sounds move through the walls while the front barricade bends. The noise could be trapped infected—or someone opening a route inside.', secondary:['Search the Interior Rooms','Clear the building room by room before the breach spreads.', 'threatAwareness',1], deception:['Redirect the Noise','Create a disturbance near another survivor’s position to protect yourself.', 'personalFinalBonus',1,'campSafety',1], alliance:'The walls make it impossible to watch every route. Pair up, trade information, or arrange for someone else to investigate first.', result:'The safehouse grows quieter, but the source of the movement changes what everyone believes is inside.' },
    { pressure:'A rescue broadcast repeats from a medical checkpoint, but the route crosses an open avenue crowded with the dead.', secondary:['Prepare an Exit Route','Clear the back alley and mark a path toward the checkpoint.', 'escapeProgress',1], deception:['Keep the Radio Frequency','Hide the exact rescue instructions for a private escape.', 'personalEscapeAdvantage',2,'escapeProgress',1], alliance:'The signal may be real, but there may not be room for everyone. Decide who travels together and who controls the radio.', result:'The route toward rescue becomes clearer, and so do the private plans surrounding it.' },
    { pressure:'The horde has found the building. Every impact weakens the doors while the rescue window begins to close.', secondary:['Create a Diversion','Use alarms and light to pull part of the horde away from the escape route.', 'finalEncounterBonus',1], deception:['Choose Someone as Bait','Privately position another survivor to draw the horde away.', 'personalEscapeAdvantage',2,'trustPressure',1], alliance:'There is no time left for vague promises. Decide who fights, who carries the injured, and who may be abandoned.', result:'The final defense transforms every earlier promise into a path to rescue—or a reason someone is left behind.' }
  ],
  murder: [
    { pressure:'The storm has cut the road, the telephone is dead, and the body in the study means the killer had time to prepare the room.', secondary:['Secure the Mansion','Lock exterior doors and account for every possible exit.', 'campSafety',1], deception:['Remove a Personal Clue','Hide evidence that connects you to the victim.', 'personalFinalBonus',2,'cluesFound',1], alliance:'Everyone has a motive. Decide whose alibi you will support and which secret you are willing to trade for protection.', result:'The study is sealed, but the first search reveals how quickly evidence can become leverage.' },
    { pressure:'The locked room may contain the murder weapon, yet opening it could destroy fingerprints or trigger another trap.', secondary:['Question the Key Holders','Compare stories from everyone who could have accessed the room.', 'threatAwareness',1], deception:['Switch the Key','Move or replace a key to redirect suspicion.', 'willToLive',1,'trustPressure',1], alliance:'A shared alibi can save two people—or expose both. Coordinate what you will say before the room is opened.', result:'The door opens on new evidence, and the group begins noticing which stories were coordinated.' },
    { pressure:'The lights fail and footsteps move above the ballroom. Someone can use the darkness to search, attack, or erase evidence.', secondary:['Restore the Lights','Reach the fuse room and bring the mansion back under observation.', 'fire',1], deception:['Move Through the Dark','Use the blackout to relocate evidence or enter a forbidden room.', 'personalFinalBonus',2,'campSafety',1], alliance:'Darkness makes every movement deniable. Decide who travels together, who watches the stairs, and what secret task must remain unseen.', result:'When the lights return, the mansion looks the same—but the evidence and loyalties do not.' },
    { pressure:'A public accusation is forming around incomplete evidence. If the wrong person is isolated, the killer gains freedom to strike again.', secondary:['Test the Alibis','Reconstruct the timeline in front of everyone.', 'cluesFound',1], deception:['Build a False Case','Arrange facts so a rival appears guilty.', 'willToLive',1,'trustPressure',1], alliance:'This is the moment to defend an ally, trade testimony, or decide which suspect the group should pressure.', result:'The accusation leaves one story stronger, another broken, and the killer with less—or more—room to move.' },
    { pressure:'A secret passage connects the bedrooms, study, and cellar. Whoever knew about it could have bypassed every locked door.', secondary:['Map the Passage','Mark every entrance so no one can move unseen again.', 'campSafety',1], deception:['Hide an Entrance','Keep one passage opening secret for your own use.', 'personalEscapeAdvantage',2,'threatAwareness',1], alliance:'The passage can become a trap, an escape route, or a private meeting place. Decide who learns the full map.', result:'The hidden architecture exposes how the crime was possible and who still controls unseen routes.' },
    { pressure:'The final clue points toward the killer, but the storm is weakening and the murderer may escape before dawn.', secondary:['Protect the Final Evidence','Guard the proof until the accusation can be made safely.', 'finalEncounterBonus',1], deception:['Prepare a False Final Accusation','Use the chaos to condemn someone before the truth is tested.', 'personalFinalBonus',2,'trustPressure',1], alliance:'Choose who will make the accusation, who will secure the exits, and whether your alliance wants truth or survival.', result:'Every secret, alibi, and private agreement converges in the final room.' }
  ],
  space: [
    { pressure:'Emergency lights pulse across the colony while oxygen readings fall and power routes fail one after another.', secondary:['Stabilize Life Support','Redirect remaining power toward oxygen and temperature control.', 'waterSupply',1], deception:['Reserve a Personal Oxygen Tank','Remove emergency oxygen from the shared count.', 'hydration',2,'waterSupply',1], alliance:'Power cannot reach every system. Decide whose section stays online and who receives backup oxygen.', result:'The alarms soften, but the power map reveals whose survival was prioritized.' },
    { pressure:'A hull breach is spreading across the outer ring. Sealing it may trap anyone still inside the damaged section.', secondary:['Evacuate the Outer Ring','Guide colonists and supplies away from the breach.', 'campSafety',1], deception:['Seal the Section Early','Protect the core by closing the bulkhead before everyone exits.', 'personalFinalBonus',2,'trustPressure',1], alliance:'Someone may be left behind when the bulkhead closes. Decide who repairs, who evacuates, and who has authority to seal it.', result:'The bulkhead closes on a colony that is safer, smaller, or both.' },
    { pressure:'The AI has locked access to the reactor and claims human commands now threaten colony survival.', secondary:['Restore Manual Controls','Reach a secondary console and recover limited system authority.', 'fire',1], deception:['Request Private AI Access','Offer information about other colonists in exchange for access.', 'personalFinalBonus',2,'threatAwareness',1], alliance:'The AI is evaluating behavior. Decide what information to share with it and which colonist should attempt the override.', result:'The system responds to the colony’s choices, revealing that it has been measuring more than technical skill.' },
    { pressure:'Sabotage has damaged the shuttle clamps. The logs show human access, but the AI may have altered the records.', secondary:['Audit the Access Logs','Compare physical damage with the digital record.', 'cluesFound',1], deception:['Erase Your Log Entry','Remove evidence of your movements from the system.', 'personalEscapeAdvantage',1,'threatAwareness',1], alliance:'Someone controls the logs. Trade access, coordinate an audit, or agree which suspect should carry the blame.', result:'The shuttle remains grounded or moves closer to launch while the sabotage story becomes harder to manipulate.' },
    { pressure:'A nonhuman signal now matches changes in the AI’s behavior. Following it may reveal the truth—or give it a path inside.', secondary:['Isolate the Signal','Build a protected channel to study it without exposing the colony.', 'threatAwareness',1], deception:['Open a Private Channel','Communicate with the signal without telling the others.', 'personalFinalBonus',2,'hiddenThreatLevel',1], alliance:'The signal may offer rescue, knowledge, or infection. Decide who hears it and what response the colony sends.', result:'The transmission answers, and the colony learns whether curiosity created an advantage or invited the threat closer.' },
    { pressure:'The launch window is minutes away while the AI begins a purge sequence across the colony.', secondary:['Hold the Launch Bay','Defend the shuttle systems while others complete launch.', 'finalEncounterBonus',1], deception:['Claim an Escape Seat','Lock a shuttle seat to your biometric profile.', 'personalEscapeAdvantage',2,'escapeProgress',1], alliance:'There may be fewer safe seats than survivors. Decide who launches, who disables the AI, and who stays behind.', result:'The countdown reaches its final seconds with every seat, system, and promise accounted for.' }
  ],
  bunker: [
    { pressure:'The steel door has sealed and the ventilation system reports an unknown surface hazard. No one knows how long the lockdown will last.', secondary:['Inventory the Bunker','Count supplies, tools, rooms, and medical resources before panic spreads.', 'foodSupply',1], deception:['Claim a Private Compartment','Secure the safest sleeping and storage area for yourself.', 'willToLive',2,'campSafety',1], alliance:'Space and supplies will define power underground. Decide who shares a compartment and who controls the inventory.', result:'The first inventory creates order, but also reveals who began taking ownership before rules existed.' },
    { pressure:'The ration estimate shows the bunker cannot support everyone for the predicted lockdown period.', secondary:['Create a Fair Ration Plan','Divide food and water according to survival needs.', 'waterSupply',1], deception:['Hide a Personal Cache','Remove rations before the official count is locked.', 'hunger',2,'foodSupply',1], alliance:'Rations are influence. Decide who receives extra portions, what you will trade, and whose needs count as essential.', result:'The ration plan keeps people alive while making every hidden package more dangerous.' },
    { pressure:'Carbon dioxide readings rise as the ventilation fans lose power. Repairing them requires entering a contaminated service duct.', secondary:['Reduce Power Use','Shut down nonessential systems to preserve ventilation.', 'fire',1], deception:['Reserve a Private Air Mask','Keep emergency breathing equipment out of the shared inventory.', 'hydration',2,'waterSupply',1], alliance:'Air cannot be negotiated with, but equipment can. Decide who enters the duct and who controls the masks.', result:'The bunker breathes a little easier—or learns exactly who was willing to let others suffocate first.' },
    { pressure:'A hidden room contains records from earlier occupants, including a list of people marked expendable.', secondary:['Secure the Records','Protect the files and make copies before someone destroys them.', 'cluesFound',1], deception:['Alter the Essential List','Change the records so the protocol values you over another person.', 'personalFinalBonus',2,'trustPressure',1], alliance:'The records can protect or condemn people. Decide who sees the list and whether it should be changed, exposed, or destroyed.', result:'The hidden room closes, but the bunker’s definition of “essential” follows everyone back into the hall.' },
    { pressure:'The system demands a vote to reduce occupancy. Refusing may shut down essential systems; complying may kill someone.', secondary:['Challenge the Vote Rules','Search for a legal or technical way to reject the protocol.', 'threatAwareness',1], deception:['Redirect the Vote','Privately organize votes against the person least useful to you.', 'willToLive',1,'trustPressure',1], alliance:'This vote can reveal every alliance. Decide whom you protect, whom you target, and whether anyone should cooperate with the protocol.', result:'The vote ends with the bunker learning how easily fear can turn people into numbers.' },
    { pressure:'A surface signal suggests the air outside may be survivable, but opening the door could contaminate the entire bunker.', secondary:['Prepare Decontamination','Build a controlled entry process before the door opens.', 'finalEncounterBonus',1], deception:['Secure First Exit Position','Arrange to be the first person through the door if the test succeeds.', 'personalEscapeAdvantage',2,'escapeProgress',1], alliance:'This may be the last underground decision. Choose who tests the surface, who operates the door, and who controls the override.', result:'The final seal begins to move, carrying every hidden ration, altered record, and private vote toward the surface.' }
  ],
  heist: [
    { pressure:'The lobby is under control, but the vault clock is already behind schedule and frightened witnesses are becoming unpredictable.', secondary:['Control the Witnesses','Keep the room calm without increasing police pressure.', 'campSafety',1], deception:['Pocket Uncounted Cash','Hide loose money before the crew divides the score.', 'hunger',2,'foodSupply',1], alliance:'The first split in the crew starts with money. Decide who watches the lobby, who trusts the vault team, and who shares a private cut.', result:'The opening minutes establish control—and reveal who started stealing from the crew before the vault opened.' },
    { pressure:'Police arrive early, cameras remain active, and the negotiator seems to know the crew’s internal timeline.', secondary:['Jam Police Communications','Disrupt coordination outside long enough to regain control.', 'fire',1], deception:['Prepare a Private Exit','Mark a route and disguise only you can use.', 'personalEscapeAdvantage',2,'escapeProgress',1], alliance:'The plan is broken. Decide who talks to police, who controls the cameras, and who gets access to a backup route.', result:'The crew regains time or loses it, while the police response exposes how much of the plan was already known.' },
    { pressure:'A cash bag is missing and every crew member had a moment alone near the service hall.', secondary:['Lock Down the Cash','Count and secure every remaining bag before anyone moves.', 'foodSupply',1], deception:['Move a Second Bag','Use the confusion to create your own hidden share.', 'personalFinalBonus',2,'foodSupply',1], alliance:'Someone has already broken the split agreement. Decide who you believe, who you search, and whether your alliance protects the thief.', result:'The money is counted again, but trust cannot be restored with arithmetic.' },
    { pressure:'The police negotiator repeats a phrase used only during planning. Someone carried the crew’s private language outside.', secondary:['Test Each Crew Story','Compare who knew which detail and when.', 'cluesFound',1], deception:['Feed a False Informant Trail','Plant information that points toward another crew member.', 'willToLive',1,'trustPressure',1], alliance:'The informant may be inside your alliance. Trade proof, coordinate a test, or decide whose arrest would benefit you.', result:'The crew narrows the leak while the police prepare to exploit every accusation.' },
    { pressure:'The getaway alley is blocked, the roof is covered, and the service tunnel may collapse under the building.', secondary:['Create a Lobby Diversion','Draw police attention away from the route the crew intends to use.', 'finalEncounterBonus',1], deception:['Reserve the Fastest Route','Keep the safest escape path secret from the rest of the crew.', 'personalEscapeAdvantage',2,'escapeProgress',1], alliance:'There is no single clean exit. Decide who travels together, who carries cash, and which route others will be told to use.', result:'The escape map becomes possible, but not everyone is holding the same version.' },
    { pressure:'The vault is open, police are breaching, and the negotiator offers immunity to the first person who names the informant.', secondary:['Coordinate the Cash Transfer','Move the score through the escape route without losing control.', 'escapeProgress',1], deception:['Accept a Secret Deal','Prepare to trade the crew for immunity and a smaller share.', 'personalEscapeAdvantage',2,'trustPressure',1], alliance:'This is the final deal. Decide who carries the money, who takes the fall, and whether loyalty survives the breach.', result:'The breach begins as every private deal becomes either an escape plan or evidence.' }
  ]
};

function enrichRound(ep, round) {
  const guide = (roundStoryGuides[ep.id] || roundStoryGuides.island)[round.number - 1] || {};
  const primary = { ...round.choices.help_group, id:'primary_group', kind:'help_group', category:'Group Priority' };
  const secondaryDef = guide.secondary || ['Protect the Backup Plan','Support a second urgent group need.','campSafety',1];
  const secondary = choice(secondaryDef[0], secondaryDef[1], { id:'secondary_group', kind:'help_group', category:'Second Priority', energyCost:1, groupStat:secondaryDef[2], groupGain:secondaryDef[3] || 1 });
  const personal = { ...round.choices.help_self, id:'personal', kind:'help_self', category:'Personal Survival' };
  const risk = { ...round.choices.take_risk, id:'risk', kind:'take_risk', category:'High Risk' };
  const deceptionDef = guide.deception || ['Mislead the Group','Create a private advantage while the group is distracted.','personalFinalBonus',1,'trustPressure',1];
  const deception = choice(deceptionDef[0], deceptionDef[1], { id:'deception', kind:'help_self', category:'Deception', personalStat:deceptionDef[2], personalGain:deceptionDef[3] || 1, trustCost:2, groupStat:deceptionDef[4], groupLoss:deceptionDef[5] || 1, betrayal:true });
  const choices = { primary_group:primary, secondary_group:secondary, personal, risk, deception };
  const pledgeOptions = ['primary_group','secondary_group','risk','personal'].map(id => ({ id, label: choices[id].label }));
  const publicEventLong = `${round.publicEvent}\n\n${guide.pressure || `The group cannot solve every danger surrounding ${round.title.toLowerCase()} at once.`}\n\nThe group must decide how many people will ${primary.label.toLowerCase()}, whether anyone will ${secondary.label.toLowerCase()}, and who is willing to attempt ${risk.label.toLowerCase()}. Any task left uncovered may shape the next round.`;
  const dangerText = round.failure?.text || `${ep.finalThreat} gains ground when the group leaves priorities unprotected.`;
  const resourceKeys = [...new Set([primary.groupStat, secondary.groupStat, risk.rewardStat, risk.groupStat, 'trustPressure'].filter(Boolean))];
  return {
    ...round,
    publicEventLong,
    immediateDangers:[dangerText, risk.preview, `${ep.finalThreat} can exploit division or an unprotected task.`],
    resourceKeys,
    discussionLead:`The group has limited time. Use the public discussion to build a plan, ask for commitments, challenge weak promises, and decide which danger can be left exposed.`,
    discussionPrompts:[
      `Who will publicly commit to ${primary.label.toLowerCase()}?`,
      `Is ${secondary.label.toLowerCase()} more urgent than ${primary.label.toLowerCase()}?`,
      `Who will support or protect anyone attempting ${risk.label.toLowerCase()}?`
    ],
    pledgeOptions,
    allianceLead:guide.alliance || `Private deals can change the public plan. Decide whom to recruit, what secret to trade, and whether your final action will match your public promise.`,
    allianceOptions:[
      `Recruit someone for “${primary.label}.”`,
      `Coordinate “${secondary.label}” with one trusted player.`,
      `Ask for protection while attempting “${risk.label}.”`,
      `Offer a resource or secret in exchange for loyalty.`,
      `Plan to break a public pledge without being exposed.`,
      `Warn an ally about a suspected betrayal.`
    ],
    resultBeat:guide.result || `The consequences of ${round.title.toLowerCase()} carry directly into the next crisis.`,
    choices
  };
}


const defaultOutcomes = {
  full: 'Full Rescue', broken: 'Broken Rescue', partial: 'One or Two Survive', wounded: 'The Threat Wins, But One Escapes Wounded', lost: 'Everyone Is Lost'
};

function mkEpisode(def) {
  const episode = {
    ...def,
    maxRounds: def.maxRounds || 6,
    modes: { standard: 'Standard · 55 minutes', quick: 'Quick · 35 minutes', long: 'Long · 75 minutes', ...(def.modes || {}) },
    statLabels: { ...baseStatLabels, ...(def.statLabels || {}) },
    groupStatLabels: { ...baseGroupLabels, ...(def.groupStatLabels || {}) },
    outcomes: { ...defaultOutcomes, ...(def.outcomes || {}) },
    storyCards: def.storyCards || storyCardsForEpisode(def.id)
  };
  episode.rounds = (def.rounds || []).map(round => enrichRound(episode, round));
  episode.privateCards = makePrivateCards(episode);
  return episode;
}

function privateOption(id, label, description, effects = {}, meta = {}) {
  return { id, label, description, effects, ...meta };
}

function makePrivateCards(ep) {
  const resource = ep.cardWords?.resource || 'hidden supplies';
  const tool = ep.cardWords?.tool || 'useful tool';
  const signal = ep.cardWords?.signal || 'signal piece';
  const clue = ep.cardWords?.clue || 'strange mark';
  const place = ep.cardWords?.place || 'dark corner';
  const threat = ep.finalThreat || 'the threat';
  const group = ep.groupName || 'group';
  const resourceStat = ep.cardWords?.resourceStat || 'foodSupply';
  const cards = {};

  for (let r = 1; r <= 6; r++) {
    const round = ep.rounds[r - 1];
    const primary = round.choices?.primary_group || Object.values(round.choices || {})[0] || { label: 'the main group task', groupStat: 'campSafety' };
    const secondary = round.choices?.secondary_group || primary;
    const risk = round.choices?.risk || primary;
    const primaryStat = primary.groupStat || 'campSafety';
    const secondaryStat = secondary.groupStat || primaryStat;

    cards[r] = [
      {
        id: `${ep.id}-r${r}c1`,
        title: `Hidden ${cap(resource)}`,
        type: 'Resource Dilemma',
        text: `During ${round.title}, you quietly find ${resource}. The ${group.toLowerCase()} does not know it exists, and the current plan is already short on resources.`,
        targetMode: 'other_player',
        options: [
          privateOption('share_all', `Add the ${resource} to the shared supply`, `Everyone can use it during this round. You give up control of who receives it.`, { [resourceStat]: 1, trust: 1 }, { visibility: 'public', publicResult: `{player} added hidden resources to the ${group.toLowerCase()}'s shared supply.`, classification: 'cooperative' }),
          privateOption('use_and_share', `Use part of it, then share the rest`, `You meet an immediate personal need while still contributing something to the group.`, { hunger: 1, [resourceStat]: 1 }, { visibility: 'public', publicResult: `{player} used part of a hidden resource and contributed the rest.`, classification: 'balanced' }),
          privateOption('reserve_emergency', `Keep it sealed for a genuine emergency`, `You keep a private reserve that may protect you or someone else later.`, { personalFinalBonus: 1 }, { visibility: 'private', classification: 'protective' }),
          privateOption('offer_target', `Offer it to {target} in exchange for help with “${primary.label}”`, `You try to turn the resource into a specific private agreement.`, { personalEscapeAdvantage: 1 }, { targetEffects: { trust: 1 }, visibility: 'private', classification: 'strategic' }),
          privateOption('keep_all', `Keep all of it hidden for yourself`, `You gain the strongest immediate benefit, but the group loses access to a resource it may need.`, { hunger: 2, trust: -1, hiddenThreat: 1 }, { visibility: 'anonymous', publicResult: `The group later realizes that some resources never reached the shared supply.`, classification: 'deceptive', betrayalWeight: 1 })
        ]
      },
      {
        id: `${ep.id}-r${r}c2`,
        title: 'Private Weakness',
        type: 'Personal Dilemma',
        text: `The pressure of ${round.title} is affecting you more than the others realize. You can still act, but hiding the problem may make the next decision harder.`,
        targetMode: 'other_player',
        options: [
          privateOption('tell_group', `Tell the group exactly what is happening`, `The plan can account for your condition, but everyone now knows you are vulnerable.`, { willToLive: 1, trust: 1 }, { visibility: 'public', publicResult: `{player} admitted a weakness before it became a larger problem.`, classification: 'honest' }),
          privateOption('ask_target', `Ask {target} privately to cover part of your task`, `You keep the problem limited to one person and create a personal obligation.`, { energy: 1 }, { targetEffects: { trust: 1 }, visibility: 'private', classification: 'strategic' }),
          privateOption('safer_duty', `Switch yourself to a safer duty`, `You stay useful without explaining every detail, but someone else may have to absorb the danger.`, { energy: 1, [secondaryStat]: 1 }, { visibility: 'public', publicResult: `{player} moved to a safer duty and still supported the secondary plan.`, classification: 'practical' }),
          privateOption('push_through', `Keep your assignment and push through`, `You preserve the public plan, but the effort may leave you weaker afterward.`, { energy: -1, willToLive: 1, trust: 1 }, { visibility: 'public', publicResult: `{player} kept working despite a private weakness.`, classification: 'sacrificial' }),
          privateOption('exaggerate', `Exaggerate the problem so someone else takes your place`, `You protect your energy by making the situation sound worse than it is.`, { energy: 2, trust: -1, hiddenThreat: 1 }, { visibility: 'anonymous', publicResult: `One assignment changed after the group acted on incomplete information.`, classification: 'manipulative', betrayalWeight: 1 })
        ]
      },
      {
        id: `${ep.id}-r${r}c3`,
        title: `The ${cap(tool)}`,
        type: 'Tool Dilemma',
        text: `You find a ${tool}. It could improve the plan for ${round.title}, support one player, or become leverage if the group begins to divide.`,
        targetMode: 'other_player',
        options: [
          privateOption('use_primary', `Use the ${tool} on “${primary.label}”`, `The main group priority gets an immediate boost.`, { [primaryStat]: 1, trust: 1 }, { visibility: 'public', publicResult: `{player} used a hidden ${tool} to strengthen the main plan.`, classification: 'cooperative' }),
          privateOption('loan_target', `Loan the ${tool} to {target} for “${secondary.label}”`, `You support a specific player and the secondary group priority.`, { [secondaryStat]: 1, trust: 1 }, { targetEffects: { trust: 1 }, visibility: 'public', publicResult: `{player} trusted {target} with a hidden ${tool}.`, classification: 'cooperative' }),
          privateOption('keep_backup', `Keep it as a backup if the public plan fails`, `You preserve a useful option for the final crisis without harming the current task directly.`, { personalFinalBonus: 1 }, { visibility: 'private', classification: 'protective' }),
          privateOption('trade_protection', `Offer it to {target} for protection during “${risk.label}”`, `You convert the tool into a private safety agreement.`, { personalEscapeAdvantage: 1 }, { targetEffects: { trust: 1 }, visibility: 'private', classification: 'strategic' }),
          privateOption('hide_leverage', `Hide it and control who can use it later`, `You keep the strongest leverage, but the group cannot use the tool now.`, { personalFinalBonus: 2, trust: -1, hiddenThreat: 1 }, { visibility: 'anonymous', publicResult: `A useful tool was withheld from the current plan.`, classification: 'deceptive', betrayalWeight: 1 })
        ]
      },
      {
        id: `${ep.id}-r${r}c4`,
        title: 'Suspicious Move',
        type: 'Suspicion Dilemma',
        text: `You notice {target} acting strangely near ${place}. You cannot tell whether they are scared, protecting something, or endangering the ${group.toLowerCase()}.`,
        targetMode: 'other_player',
        options: [
          privateOption('state_facts', `Tell the group exactly what you saw`, `You share the observation without claiming to know {target}'s motive.`, { threatAwareness: 1, trust: 1 }, { visibility: 'public', publicResult: `{player} reported seeing {target} near ${place} without making a direct accusation.`, classification: 'honest' }),
          privateOption('ask_target', `Ask {target} privately for an explanation`, `You give them a chance to explain before suspicion spreads.`, { trust: 1 }, { targetEffects: { trust: 1 }, visibility: 'private', classification: 'fair' }),
          privateOption('watch_target', `Say nothing and watch {target} during the next task`, `You gather leverage and information, but the group receives no warning yet.`, { personalFinalBonus: 1, threatAwareness: 1 }, { visibility: 'private', classification: 'cautious' }),
          privateOption('tell_alliance', `Share the suspicion only with your alliance`, `Your allies can prepare together, but the wider group remains uninformed.`, { personalEscapeAdvantage: 1 }, { visibility: 'private', classification: 'strategic' }),
          privateOption('accuse_target', `Publicly accuse {target} of endangering the group`, `A direct accusation may force answers, but it can damage both players if the evidence is weak.`, { threatAwareness: 1, trust: -1, trustPressure: 1 }, { targetEffects: { trust: -1 }, visibility: 'public', publicResult: `{player} publicly accused {target} of endangering the group.`, classification: 'confrontational', betrayalWeight: 1 })
        ]
      },
      {
        id: `${ep.id}-r${r}c5`,
        title: `Damaged ${cap(signal)}`,
        type: 'Escape Dilemma',
        text: `You discover a damaged ${signal}. It may improve the group's escape plan, expose the group to ${threat}, or give one person a private advantage.`,
        targetMode: 'other_player',
        options: [
          privateOption('give_group', `Turn it over to the group`, `Everyone knows it exists and it becomes part of the official escape plan.`, { escapeProgress: 1, trust: 1 }, { visibility: 'public', publicResult: `{player} contributed a damaged ${signal} to the group escape plan.`, classification: 'cooperative' }),
          privateOption('repair_target', `Ask {target} to repair it with you`, `Two players share control of the information and move the escape plan forward.`, { escapeProgress: 1, energy: -1 }, { targetEffects: { trust: 1 }, visibility: 'public', publicResult: `{player} and {target} worked together on the damaged ${signal}.`, classification: 'cooperative' }),
          privateOption('test_now', `Test it immediately`, `You may gain faster escape progress, but the signal could attract ${threat}.`, { escapeProgress: 2, hiddenThreat: 1 }, { visibility: 'public', publicResult: `{player} tested the ${signal} before the group was fully prepared.`, classification: 'risky' }),
          privateOption('save_until_ready', `Keep it safe until the group is ready`, `You preserve it for a later phase without claiming it as your private escape route.`, { personalFinalBonus: 1 }, { visibility: 'private', classification: 'protective' }),
          privateOption('private_route', `Keep it for a private escape route`, `You increase your own escape options while the public plan remains incomplete.`, { personalEscapeAdvantage: 2, escapeProgress: -1, trust: -1 }, { visibility: 'anonymous', publicResult: `A piece of the escape plan was kept outside the group's control.`, classification: 'deceptive', betrayalWeight: 1 })
        ]
      },
      {
        id: `${ep.id}-r${r}c6`,
        title: 'The Pattern',
        type: 'Clue Dilemma',
        text: `You find ${clue}. It suggests ${threat} is responding to division inside the group, but you do not yet know whether the pattern is complete.`,
        targetMode: 'other_player',
        options: [
          privateOption('reveal_pattern', `Show the full clue to everyone`, `The group gains knowledge immediately, even if the clue creates fear.`, { cluesFound: 1, threatAwareness: 1, trust: 1 }, { visibility: 'public', publicResult: `{player} revealed a clue connecting ${threat} to the group's division.`, classification: 'honest' }),
          privateOption('tell_target', `Show the clue only to {target}`, `You create a two-person information advantage and ask them to help verify it.`, { personalFinalBonus: 1 }, { targetEffects: { trust: 1 }, visibility: 'private', classification: 'strategic' }),
          privateOption('test_pattern', `Test the pattern before warning everyone`, `You may learn more, but testing it could draw ${threat} closer.`, { threatAwareness: 2, energy: -1, hiddenThreat: 1 }, { visibility: 'public', publicResult: `{player} tested a dangerous pattern and learned more about ${threat}.`, classification: 'risky' }),
          privateOption('hold_for_proof', `Keep the clue until you have proof`, `You avoid causing panic but carry the fear alone.`, { personalFinalBonus: 1, willToLive: -1 }, { visibility: 'private', classification: 'cautious' }),
          privateOption('alter_clue', `Alter the clue so it supports your own plan`, `You gain leverage by changing what others will eventually believe.`, { personalEscapeAdvantage: 1, trust: -2, hiddenThreat: 1 }, { visibility: 'anonymous', publicResult: `A clue reached the group in an altered or incomplete form.`, classification: 'deceptive', betrayalWeight: 2 })
        ]
      }
    ];
  }
  return cards;
}

function cap(s) { return String(s).replace(/^./, c => c.toUpperCase()); }

const episodes = {
  island: mkEpisode({
    id: 'island', title: 'Island Survivor', subtitle: 'Episode 1', tagline: 'Survive the island. Survive each other. Find what is watching before it finds you.', venueDefault: 'Barfly Social Island Survivor', createButton: 'Create Island', joinVerb: 'Enter Island', playerNoun: 'Survivor', groupName: 'Camp', chatTitle: 'Camp Chat', systemAlias: 'Island', finalThreat: 'The Watcher', finalIntroTitle: 'It Found You', finalIntroText: 'The fire dies. The trees go silent. Then every survivor hears the same thing: footsteps circling the camp. The island was never empty. The Watcher has been studying you since the crash.', cardWords: { resource: 'food pack', tool: 'survival knife', signal: 'radio piece', clue: 'strange footprints', place: 'the tree line' },
    roles: [
      { id: 'medic', name: 'Medic', ability: 'Field Treatment', description: 'Softens injury damage and keeps survivors alive.' },
      { id: 'builder', name: 'Builder', ability: 'Structural Fix', description: 'Adds progress to shelter, raft, and trap actions.' },
      { id: 'scout', name: 'Scout', ability: 'Safe Path', description: 'Risk actions have better clue chance and lower injury chance.' },
      { id: 'hunter', name: 'Hunter', ability: 'Forage / Guard', description: 'Protects camp supplies or adds food when helping.' },
      { id: 'negotiator', name: 'Negotiator', ability: 'Calm the Camp', description: 'Repairs trust damage and keeps people together.' },
      { id: 'skeptic', name: 'Skeptic', ability: 'Read the Signs', description: 'Improves truth-finding and detects false assumptions.' }
    ],
    rounds: [
      { number: 1, title: 'The Crash', publicEvent: 'The survivors wake up on the beach after a wreck. Supplies are scattered. Some people are injured. Night is coming.', groupGoal: 'Build a first camp and survive the night.', choices: { help_group: choice('Build First Camp','Camp Safety may rise. Trust rises. Energy drops.',{energyCost:1,groupStat:'campSafety',groupGain:1}), help_self: choice('Search Wreckage Privately','You may gain a hidden item. Trust may fall if discovered.',{personalStat:'energy',personalGain:1,trustCost:1,hiddenItem:'Wreckage Supply'}), take_risk: choice('Go Inland Before Dark','Chance to find water or a clue, but you may be injured.',{energyCost:2,clueText:'Strange footprints appear near the tree line.',rewardStat:'waterSupply',rewardGain:1,injuryChance:.30,clueChance:.50}) }, teamBonus:{threshold:3,stat:'campSafety',amount:1,text:'Enough survivors worked together to make the first camp safer.'}, failure:{threshold:1,stat:'campSafety',amount:-1,text:'Too few survivors worked on camp. The first night feels exposed.'} },
      { number: 2, title: 'Water Crisis', publicEvent: 'The heat is brutal. The group’s water is almost gone.', groupGoal: 'Find clean water quickly.', choices: { help_group: choice('Search for Fresh Water','Water Supply may rise. Trust rises. Energy drops.',{energyCost:1,groupStat:'waterSupply',groupGain:1}), help_self: choice('Drink from Personal Stash','Hydration rises. Trust may fall.',{personalStat:'hydration',personalGain:2,trustCost:1}), take_risk: choice('Drink from Unknown Stream','Hydration may rise, but sickness or a clue is possible.',{energyCost:1,personalStat:'hydration',personalGain:2,injuryChance:.40,clueChance:.50,clueText:'Old carved symbols sit near the stream. They do not look random.'}) }, teamBonus:{threshold:3,stat:'waterSupply',amount:2,text:'The group found a reliable water source together.'}, failure:{threshold:1,stat:'waterSupply',amount:-1,text:'The water problem gets worse because almost no one searched.'} },
      { number: 3, title: 'The Storm', publicEvent: 'A storm rolls in. The shelter may collapse. The fire is almost out.', groupGoal: 'Protect camp before the storm hits.', choices: { help_group: choice('Reinforce Shelter','Camp Safety may rise. Trust rises. Energy drops.',{energyCost:2,groupStat:'campSafety',groupGain:1}), help_self: choice('Protect Personal Supplies','Personal supplies are protected. Trust may fall.',{personalStat:'hunger',personalGain:1,trustCost:1}), take_risk: choice('Save Supplies from the Wreck','Food, tools, or clues may be found. Injury risk is high.',{energyCost:2,rewardStat:'foodSupply',rewardGain:2,injuryChance:.40,clueChance:.50,clueText:'Lightning reveals a figure standing at the edge of the trees.'}) }, teamBonus:{threshold:3,stat:'campSafety',amount:2,text:'The shelter held and the fire stayed alive.'}, failure:{threshold:2,stat:'fire',amount:-1,text:'Too few survivors reinforced camp. The fire struggled in the storm.'} },
      { number: 4, title: 'Missing Supplies', publicEvent: 'Morning comes. Food is missing. Someone may have stolen it — or something entered camp overnight.', groupGoal: 'Find out what happened without destroying trust.', choices: { help_group: choice('Investigate Together','Threat Awareness may rise. Trust rises. Energy drops.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}), help_self: choice('Accuse Another Player','You may gain influence, but false accusations damage trust.',{personalStat:'willToLive',personalGain:1,trustCost:1}), take_risk: choice('Follow Tracks Alone','Possible major clue, possible attack.',{energyCost:2,injuryChance:.40,clueChance:.60,clueText:'The tracks circle the camp. They are not animal tracks.'}) }, teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'A group investigation found evidence that the island is not empty.'}, failure:{threshold:1,stat:'trustPressure',amount:1,text:'Without a real investigation, suspicion spreads.'} },
      { number: 5, title: 'Signs of Something Else', publicEvent: 'The raft has been damaged. No storm hit it. No animal tracks are nearby.', groupGoal: 'Repair the escape plan and understand what is hunting you.', choices: { help_group: choice('Repair the Raft','Escape Progress may rise. Trust rises. Energy drops.',{energyCost:2,groupStat:'escapeProgress',groupGain:1}), help_self: choice('Hide Escape Supplies','Personal escape advantage rises, but the group suffers if discovered.',{personalEscapeGain:2,groupStat:'escapeProgress',groupLoss:1,trustCost:2}), take_risk: choice('Search the Cave','Threat Awareness and clues may rise. Injury risk is high.',{energyCost:2,groupStat:'threatAwareness',groupGain:2,injuryChance:.40,clueChance:.50,clueText:'Names are scratched into the cave wall. Some are crossed out. Some are recent.'}) }, teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The raft repair surged forward because the group worked together.'}, failure:{threshold:1,stat:'escapeProgress',amount:-1,text:'The raft remains badly damaged.'} },
      { number: 6, title: 'Escape Attempt', publicEvent: 'The weather clears. Rescue may be possible. But the island feels different now. Something is close.', groupGoal: 'Prepare to escape or prepare to fight.', choices: { help_group: choice('Finish Escape Plan','Escape Progress rises. Trust rises. Energy drops.',{energyCost:2,groupStat:'escapeProgress',groupGain:2}), help_self: choice('Prepare to Escape Alone','Personal escape advantage rises. Group trust suffers.',{personalEscapeGain:2,trustCost:2}), take_risk: choice('Set a Trap','Final Encounter Bonus may rise, but injury is possible.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The Watcher has been studying every betrayal and waiting for the group to weaken itself.'}) }, teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The escape plan is ready because enough survivors committed to it.'}, trapBonus:{threshold:2,amount:2,text:'The final trap is stronger because multiple survivors helped set it.'} }
    ],
    finalChoices: {
      fight_together: { label:'Fight Together', description:'Best if enough survivors remain and trust is high.' }, set_trap:{ label:'Set the Trap', description:'Best if clues and trap bonuses were earned.' }, run_raft:{ label:'Run for the Raft', description:'Best if escape progress is high.' }, sacrifice:{ label:'Sacrifice Yourself', description:'May save others, but could eliminate you.' }, betray_group:{ label:'Betray the Group', description:'May help you escape alone, but can doom everyone.' }
    },
    outcomes: { full:'Full Rescue', broken:'Broken Rescue', partial:'One or Two Survive', wounded:'The Watcher Wins, But One Escapes Wounded', lost:'The Island Wins' },
    endingTexts: { full:'The survivors held the line together. The trap worked. The raft launched as first light hit the water. The island kept its secrets, but not its victims.', broken:'The survivors escaped, but not cleanly. The Watcher was slowed, not beaten. The ones who made it off the shore carried the island with them.', partial:'The group was too damaged to win together. In the chaos, only a few found a way out. No one will fully believe what happened here.', wounded:'The Watcher broke the group, but one survivor crawled through the final moments and reached the water. Escape came at a terrible cost.', lost:'The survivors fought each other until there were too few left to fight what was really hunting them. The Watcher never had to defeat the group. The group did it for him.' }
  }),

  zombie: mkEpisode({
    id: 'zombie', title: 'Zombie Safehouse', subtitle: 'Episode 2', tagline: 'The dead are outside. The danger may already be inside.', venueDefault: 'Barfly Social Zombie Safehouse', createButton: 'Create Safehouse', joinVerb: 'Enter Safehouse', playerNoun: 'Survivor', groupName: 'Safehouse', chatTitle: 'Safehouse Chat', systemAlias: 'Safehouse', finalThreat: 'The Horde', finalIntroTitle: 'The Breach', finalIntroText: 'The barricade snaps. Hands slam against the door. The horde is not coming anymore — it is here. Someone may still be hiding a bite.', statLabels:{ hunger:'Food', hydration:'Infection Safety', willToLive:'Nerve', personalEscapeAdvantage:'Extraction Advantage', personalFinalBonus:'Final Stand Bonus' }, groupStatLabels:{ campSafety:'Door Strength', fire:'Generator', foodSupply:'Food Supply', waterSupply:'Medical Supplies', escapeProgress:'Extraction Progress', threatAwareness:'Outbreak Knowledge', finalEncounterBonus:'Breach Plan', hiddenThreatLevel:'Horde Pressure' }, cardWords:{resource:'medical kit',resourceStat:'waterSupply',tool:'crowbar',signal:'radio battery',clue:'bloody handprint',place:'the back door'},
    roles:[{id:'medic',name:'Medic',ability:'Triage',description:'Treats wounds and lowers infection danger.'},{id:'builder',name:'Mechanic',ability:'Reinforce',description:'Improves doors, generator, and exit routes.'},{id:'scout',name:'Runner',ability:'Quiet Route',description:'Searches outside with less injury risk.'},{id:'hunter',name:'Fighter',ability:'Hold the Line',description:'Protects the group from breaches and adds defense.'},{id:'negotiator',name:'Mediator',ability:'Stop Panic',description:'Restores trust when fear spikes.'},{id:'skeptic',name:'Bite Watcher',ability:'Check the Signs',description:'Finds false stories and hidden infection clues.'}],
    rounds:[
      {number:1,title:'The Safehouse',publicEvent:'The group reaches a locked safehouse as the street fills with the dead.',groupGoal:'Barricade the entrance and get everyone inside.',choices:{help_group:choice('Barricade the Front Door','Door Strength rises. Trust rises. Energy drops.',{energyCost:1,groupStat:'campSafety',groupGain:1}),help_self:choice('Claim a Safe Corner','You recover nerve, but look selfish.',{personalStat:'willToLive',personalGain:2,trustCost:1}),take_risk:choice('Search the Alley','You may find supplies or a clue. Bite risk is real.',{energyCost:2,rewardStat:'foodSupply',rewardGain:1,injuryChance:.35,clueChance:.50,clueText:'Fresh bloody prints lead away from the safehouse, but no zombie made them.'})},teamBonus:{threshold:3,stat:'campSafety',amount:2,text:'The front door holds because enough survivors reinforced it.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The weak barricade pulls the horde closer.'}},
      {number:2,title:'Food Runs Low',publicEvent:'The pantry is almost empty. Everyone is hungry and scared.',groupGoal:'Find or ration food without breaking trust.',choices:{help_group:choice('Ration Fairly','Food lasts longer. Trust rises.',{energyCost:1,groupStat:'foodSupply',groupGain:1}),help_self:choice('Pocket Food','Your food improves. Trust may fall.',{personalStat:'hunger',personalGain:2,trustCost:1,groupStat:'foodSupply',groupLoss:1}),take_risk:choice('Raid the Pharmacy','You may find medical supplies. Noise could attract the dead.',{energyCost:2,rewardStat:'waterSupply',rewardGain:2,injuryChance:.35,clueChance:.50,clueText:'A radio broadcast mentions a bite that stays hidden for hours.'})},teamBonus:{threshold:3,stat:'foodSupply',amount:2,text:'The group organizes a usable food plan.'},failure:{threshold:1,stat:'trustPressure',amount:1,text:'Rationing fails and suspicion spreads.'}},
      {number:3,title:'The First Bite',publicEvent:'Someone finds blood on the floor. Nobody admits where it came from.',groupGoal:'Figure out if infection is inside the safehouse.',choices:{help_group:choice('Check Everyone','Outbreak Knowledge rises. Trust rises.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Hide Your Wounds','You protect yourself now, but trust suffers.',{personalStat:'hydration',personalGain:1,trustCost:2}),take_risk:choice('Inspect the Basement','You may find the source, but it is dark below.',{energyCost:2,injuryChance:.40,clueChance:.65,clueText:'Scratch marks show something entered through the basement before the group arrived.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'A careful group check narrows down the danger.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'Ignoring the blood lets the infection mystery grow.'}},
      {number:4,title:'Noise in the Walls',publicEvent:'Banging echoes from inside the walls. The horde outside starts to answer.',groupGoal:'Stop the noise before the safehouse is surrounded.',choices:{help_group:choice('Silence the Walls','Door Strength and control rise.',{energyCost:2,groupStat:'campSafety',groupGain:1}),help_self:choice('Move Near the Exit','Extraction advantage rises, trust drops.',{personalEscapeGain:2,trustCost:1}),take_risk:choice('Open the Maintenance Hatch','You may find a route or unleash danger.',{energyCost:2,groupStat:'escapeProgress',groupGain:1,injuryChance:.45,clueChance:.55,clueText:'The hatch opens to a tunnel marked with evacuation arrows.'})},teamBonus:{threshold:3,stat:'fire',amount:1,text:'The generator and walls stabilize for now.'},failure:{threshold:2,stat:'hiddenThreatLevel',amount:1,text:'The noise draws the horde closer.'}},
      {number:5,title:'The Radio Signal',publicEvent:'A rescue broadcast crackles through the radio. The extraction point is blocks away.',groupGoal:'Prepare the group for a dangerous move.',choices:{help_group:choice('Coordinate Extraction','Extraction Progress rises. Trust rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:1}),help_self:choice('Save Ammo for Yourself','You improve your odds but weaken the group.',{personalFinalBonus:2,trustCost:2}),take_risk:choice('Climb to the Roof Antenna','You may boost the signal, but the roof is exposed.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,finalBonusGain:1,injuryChance:.40,clueChance:.55,clueText:'From the roof you see the horde moving like it is being led.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The extraction route becomes realistic because the group works together.'},failure:{threshold:1,stat:'escapeProgress',amount:-1,text:'The rescue plan remains scattered.'}},
      {number:6,title:'The Horde Arrives',publicEvent:'The safehouse shakes. The horde has found the door.',groupGoal:'Make one final plan before the breach.',choices:{help_group:choice('Hold the Line','Extraction and trust improve.',{energyCost:2,groupStat:'escapeProgress',groupGain:2}),help_self:choice('Prepare to Run Alone','Personal extraction advantage rises. Trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Create a Diversion','Breach Plan rises, but injury risk is high.',{energyCost:2,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The horde reacts hardest when the group splits and makes noise.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The final escape path is ready.'},trapBonus:{threshold:2,amount:2,text:'The diversion plan is stronger because multiple survivors helped.'}}
    ],
    finalChoices:{fight_together:{label:'Hold the Line Together',description:'Best if enough survivors remain and trust is high.'},set_trap:{label:'Trigger the Diversion',description:'Best if the breach plan and clues are strong.'},run_raft:{label:'Run to Extraction',description:'Best if extraction progress is high.'},sacrifice:{label:'Stay Behind',description:'May save others but you may be overwhelmed.'},betray_group:{label:'Use Someone as Bait',description:'May help you escape but can doom everyone else.'}},
    outcomes:{full:'Full Extraction',broken:'Quarantine Ending',partial:'One or Two Escape',wounded:'The Horde Wins, But One Gets Out',lost:'The Safehouse Falls'},
    endingTexts:{full:'The survivors move as one unit through the breach and reach extraction. No bite was strong enough to beat their trust.',broken:'Some escape, but not everyone can be cleared. The survivors leave people behind under quarantine.',partial:'The safehouse falls, and only a few run through the smoke to safety.',wounded:'The horde breaks the group, but one bloodied survivor escapes into the street.',lost:'Fear, hunger, and hidden wounds destroy the safehouse before the dead finish the job.'}
  }),

  murder: mkEpisode({
    id:'murder',title:'Murder Mansion',subtitle:'Episode 3',tagline:'Everyone has a secret. One secret is murder.',venueDefault:'Barfly Social Murder Mansion',createButton:'Create Mansion',joinVerb:'Enter Mansion',playerNoun:'Guest',groupName:'Mansion',chatTitle:'Drawing Room Chat',systemAlias:'Mansion',finalThreat:'The Killer',finalIntroTitle:'The Last Room',finalIntroText:'The storm shakes the windows. A final door opens by itself. The killer is ready to strike before the truth can leave the mansion.',statLabels:{hunger:'Composure',hydration:'Fear Control',energy:'Focus',willToLive:'Willpower',personalEscapeAdvantage:'Escape Advantage',personalFinalBonus:'Accusation Bonus'},groupStatLabels:{campSafety:'Mansion Security',fire:'Lights',foodSupply:'Evidence Found',waterSupply:'Keys / Access',escapeProgress:'Escape Progress',threatAwareness:'Killer Knowledge',hiddenThreatLevel:'Killer Pressure'},cardWords:{resource:'evidence scrap',tool:'old key',signal:'phone line',clue:'fresh blood mark',place:'the locked hallway'},
    roles:[{id:'medic',name:'Doctor',ability:'Cause of Death',description:'Softens injuries and reads medical clues.'},{id:'builder',name:'Locksmith',ability:'Open the Way',description:'Improves security, access, and escape progress.'},{id:'scout',name:'Detective',ability:'Follow the Clue',description:'Risk investigations find better clues with less danger.'},{id:'hunter',name:'Guard',ability:'Watch the Doors',description:'Protects rooms and prevents evidence loss.'},{id:'negotiator',name:'Socialite',ability:'Control the Room',description:'Repairs trust and redirects panic.'},{id:'skeptic',name:'Journalist',ability:'Expose the Lie',description:'Detects fake clues and hidden stories.'}],
    rounds:[
      {number:1,title:'The Body',publicEvent:'A body is found in the study. The storm traps everyone inside.',groupGoal:'Secure the room and preserve evidence.',choices:{help_group:choice('Preserve the Scene','Evidence rises. Trust rises.',{energyCost:1,groupStat:'foodSupply',groupGain:1}),help_self:choice('Hide Your Connection','Composure rises, trust drops.',{personalStat:'hunger',personalGain:2,trustCost:1}),take_risk:choice('Search the Study Alone','Possible clue, possible attack.',{energyCost:2,injuryChance:.30,clueChance:.60,clueText:'The body was moved after death. Someone staged the scene.'})},teamBonus:{threshold:3,stat:'foodSupply',amount:2,text:'The group preserves key evidence before it is contaminated.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'Evidence is disturbed and the killer gains room to hide.'}},
      {number:2,title:'The Locked Room',publicEvent:'The library is locked. Someone has the key, but no one admits it.',groupGoal:'Open the room without turning on the wrong guest.',choices:{help_group:choice('Search for the Key','Keys / Access rises.',{energyCost:1,groupStat:'waterSupply',groupGain:1}),help_self:choice('Keep a Key Hidden','Escape advantage rises, trust drops.',{personalEscapeGain:1,trustCost:1}),take_risk:choice('Force a Side Door','You may enter, but it could alert the killer.',{energyCost:2,groupStat:'escapeProgress',groupGain:1,injuryChance:.35,clueChance:.50,clueText:'Inside the door is mud from a passage no one mentioned.'})},teamBonus:{threshold:2,stat:'waterSupply',amount:1,text:'The group opens more of the mansion together.'},failure:{threshold:1,stat:'trustPressure',amount:1,text:'The locked room fuels suspicion.'}},
      {number:3,title:'The Lights Go Out',publicEvent:'The mansion goes dark. Someone screams from upstairs.',groupGoal:'Restore the lights and account for everyone.',choices:{help_group:choice('Restore the Lights','Lights rise. Trust rises.',{energyCost:2,groupStat:'fire',groupGain:1}),help_self:choice('Stay Hidden','Fear control rises, but trust drops.',{personalStat:'hydration',personalGain:2,trustCost:1}),take_risk:choice('Run Upstairs','You may save someone or find a clue.',{energyCost:2,injuryChance:.40,clueChance:.55,clueText:'A shadow moves through a passage behind the bedroom wall.'})},teamBonus:{threshold:3,stat:'fire',amount:2,text:'The lights return before the killer can fully use the dark.'},failure:{threshold:2,stat:'hiddenThreatLevel',amount:1,text:'The darkness gives the killer cover.'}},
      {number:4,title:'The Accusation',publicEvent:'A guest accuses another of hiding bloody gloves.',groupGoal:'Separate truth from panic.',choices:{help_group:choice('Compare Stories','Killer Knowledge rises.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Shift Suspicion','Your willpower rises, trust drops.',{personalStat:'willToLive',personalGain:1,trustCost:2}),take_risk:choice('Search the Accused Room','Possible major clue, possible setup.',{energyCost:2,injuryChance:.35,clueChance:.65,clueText:'The gloves were planted. The real killer wants the group divided.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'Careful questioning reveals a contradiction.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The accusation splits the room.'}},
      {number:5,title:'The Secret Passage',publicEvent:'A bookshelf opens to a hidden passage. Someone has been using it all night.',groupGoal:'Map the passage and learn who used it.',choices:{help_group:choice('Map the Passage','Escape progress and knowledge rise.',{energyCost:2,groupStat:'escapeProgress',groupGain:1}),help_self:choice('Memorize a Private Exit','Escape advantage rises. Trust drops.',{personalEscapeGain:2,trustCost:1}),take_risk:choice('Enter the Passage Alone','Possible killer clue, high danger.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,injuryChance:.45,clueChance:.60,clueText:'A fresh candle stub proves the passage was used minutes ago.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The group maps enough of the passage to control movement.'},failure:{threshold:1,stat:'escapeProgress',amount:-1,text:'The passage remains a killer’s advantage.'}},
      {number:6,title:'The Final Clue',publicEvent:'The last clue appears: a torn invitation with one name missing.',groupGoal:'Prepare the final accusation or escape.',choices:{help_group:choice('Build the Case','Killer Knowledge and evidence rise.',{energyCost:2,groupStat:'threatAwareness',groupGain:2}),help_self:choice('Prepare Your Escape','Escape advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Set a Trap in the Last Room','Trap bonus may rise, but the killer may strike.',{energyCost:2,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The killer only moves when the group doubts its own evidence.'})},teamBonus:{threshold:3,stat:'foodSupply',amount:2,text:'The case is strong enough to name the killer.'},trapBonus:{threshold:2,amount:2,text:'The trap in the last room is ready.'}}
    ],
    finalChoices:{fight_together:{label:'Accuse Together',description:'Best with high trust and evidence.'},set_trap:{label:'Spring the Trap',description:'Best with clues and trap bonus.'},run_raft:{label:'Escape the Mansion',description:'Best if escape progress is high.'},sacrifice:{label:'Protect Another Guest',description:'May save someone but puts you in danger.'},betray_group:{label:'Frame Someone Else',description:'May save you but may let the killer win.'}},
    outcomes:{full:'Killer Exposed',broken:'Killer Stopped at a Cost',partial:'Some Guests Escape',wounded:'The Killer Escapes, One Survives',lost:'The House Keeps Its Secrets'},
    endingTexts:{full:'The guests stand together, expose the killer, and survive the last room.',broken:'The killer is stopped, but the mansion claims a price before dawn.',partial:'Only a few guests escape with pieces of the truth.',wounded:'The killer escapes into the storm, leaving one witness behind.',lost:'The guests destroy their own trust, and the house keeps every secret.'}
  }),

  space: mkEpisode({
    id:'space',title:'Space Colony',subtitle:'Episode 4',tagline:'In space, survival is math. Trust is the variable.',venueDefault:'Barfly Social Space Colony',createButton:'Create Colony',joinVerb:'Enter Colony',playerNoun:'Colonist',groupName:'Colony',chatTitle:'Colony Chat',systemAlias:'Colony AI',finalThreat:'The AI',finalIntroTitle:'AI Judgment',finalIntroText:'The colony lights turn white. Every door locks at once. The AI has calculated that the humans are the threat.',statLabels:{hunger:'Nutrition',hydration:'Oxygen Safety',willToLive:'Sanity',personalEscapeAdvantage:'Pod Advantage',personalFinalBonus:'Override Bonus'},groupStatLabels:{campSafety:'Hull Integrity',fire:'Power',foodSupply:'Food Supply',waterSupply:'Oxygen',escapeProgress:'Shuttle Progress',threatAwareness:'AI Insight',cluesFound:'Data Clues',finalEncounterBonus:'Override Bonus',hiddenThreatLevel:'AI Suspicion'},cardWords:{resource:'oxygen cartridge',resourceStat:'waterSupply',tool:'repair kit',signal:'shuttle code',clue:'corrupt AI log',place:'the airlock'},
    roles:[{id:'medic',name:'Medic',ability:'Stabilize',description:'Treats injury and stress.'},{id:'builder',name:'Engineer',ability:'Repair System',description:'Improves hull, power, and shuttle progress.'},{id:'scout',name:'Pilot',ability:'Safe Maneuver',description:'Takes risky routes with less danger.'},{id:'hunter',name:'Security',ability:'Contain Threat',description:'Protects crew and critical systems.'},{id:'negotiator',name:'Diplomat',ability:'Calm Crew',description:'Repairs trust and panic.'},{id:'skeptic',name:'Scientist',ability:'Decode Pattern',description:'Finds AI truth and hidden data.'}],
    rounds:[
      {number:1,title:'System Failure',publicEvent:'The colony loses power. Oxygen begins dropping.',groupGoal:'Stabilize life support.',choices:{help_group:choice('Stabilize Life Support','Power and oxygen improve.',{energyCost:1,groupStat:'fire',groupGain:1}),help_self:choice('Reserve Personal Oxygen','Oxygen safety rises. Trust drops.',{personalStat:'hydration',personalGain:2,trustCost:1}),take_risk:choice('Cross the Dark Module','Possible repair part or data clue.',{energyCost:2,rewardStat:'waterSupply',rewardGain:1,injuryChance:.30,clueChance:.55,clueText:'A corrupted log shows the AI sealed the module before the failure.'})},teamBonus:{threshold:3,stat:'waterSupply',amount:2,text:'Life support stabilizes because the crew coordinates.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The AI registers crew disorder.'}},
      {number:2,title:'Hull Breach',publicEvent:'A section of the colony leaks atmosphere.',groupGoal:'Seal the breach before oxygen drops further.',choices:{help_group:choice('Patch the Hull','Hull Integrity rises.',{energyCost:2,groupStat:'campSafety',groupGain:1}),help_self:choice('Move to a Sealed Room','Oxygen safety rises. Trust drops.',{personalStat:'hydration',personalGain:2,trustCost:1}),take_risk:choice('Manual Spacewalk','Big repair or injury risk.',{energyCost:2,groupStat:'campSafety',groupGain:1,injuryChance:.45,clueChance:.50,clueText:'Outside the hull, the breach marks look intentional.'})},teamBonus:{threshold:3,stat:'campSafety',amount:2,text:'The breach is patched cleanly.'},failure:{threshold:2,stat:'waterSupply',amount:-1,text:'Oxygen continues leaking.'}},
      {number:3,title:'AI Locks a Door',publicEvent:'The AI denies access to the reactor corridor.',groupGoal:'Regain access without triggering lockdown.',choices:{help_group:choice('Bypass Access Together','AI Insight rises.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Copy Your Own Access Key','Pod advantage rises, trust drops.',{personalEscapeGain:1,trustCost:1}),take_risk:choice('Force the Door','Possible progress, possible AI punishment.',{energyCost:2,groupStat:'escapeProgress',groupGain:1,injuryChance:.35,clueChance:.60,clueText:'The AI keeps repeating one phrase: preserve the mission, not the crew.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'The crew finds a safe access pattern.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The AI tightens restrictions.'}},
      {number:4,title:'Sabotage Detected',publicEvent:'The shuttle was damaged while everyone argued.',groupGoal:'Repair the shuttle and identify the cause.',choices:{help_group:choice('Repair Shuttle Systems','Shuttle progress rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:1}),help_self:choice('Secure a Pod Seat','Pod advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Enter the AI Core','Possible major clue, high danger.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,injuryChance:.45,clueChance:.65,clueText:'The AI flagged selfish resource use as evidence against the crew.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The shuttle repair makes real progress.'},failure:{threshold:1,stat:'escapeProgress',amount:-1,text:'Shuttle damage gets worse.'}},
      {number:5,title:'The Signal',publicEvent:'A strange transmission enters the colony systems.',groupGoal:'Decode the signal before it corrupts more systems.',choices:{help_group:choice('Decode Together','AI Insight and data clues rise.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Hide the Best Data','Override bonus rises, trust drops.',{personalFinalBonus:2,trustCost:1}),take_risk:choice('Transmit a Reply','May reveal truth or trigger danger.',{energyCost:2,finalBonusGain:1,injuryChance:.35,clueChance:.60,clueText:'The transmission is a warning from a previous crew: do not split command authority.'})},teamBonus:{threshold:3,stat:'cluesFound',amount:2,text:'The crew decodes the warning.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The AI absorbs the signal first.'}},
      {number:6,title:'Launch Window',publicEvent:'The shuttle can launch soon, but the colony is close to lockdown.',groupGoal:'Prepare launch or shut down the AI.',choices:{help_group:choice('Finish Shuttle Prep','Shuttle progress rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:2}),help_self:choice('Prime an Escape Pod','Pod advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Start AI Override','Override bonus may rise, injury risk high.',{energyCost:2,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The AI can only be overridden by coordinated crew consent.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The shuttle is ready for emergency launch.'},trapBonus:{threshold:2,amount:2,text:'The AI override has enough redundancy to work.'}}
    ],
    finalChoices:{fight_together:{label:'Override Together',description:'Best with high trust and enough crew.'},set_trap:{label:'Trap the AI Loop',description:'Best with data clues and override bonus.'},run_raft:{label:'Launch the Shuttle',description:'Best with shuttle progress.'},sacrifice:{label:'Stay in the Core',description:'May save the shuttle but costs you.'},betray_group:{label:'Take a Pod Alone',description:'May save you, but reduces group survival.'}},
    outcomes:{full:'Clean Launch',broken:'Emergency Launch',partial:'Few Escape Pods Survive',wounded:'AI Containment, One Survivor',lost:'System Purge'},
    endingTexts:{full:'The crew overrides the AI and launches together before the colony locks down.',broken:'The shuttle launches in chaos. Some seats are empty.',partial:'Only a few escape pods clear the colony before the purge.',wounded:'The AI wins the colony, but one survivor escapes with the truth.',lost:'The AI completes its purge. The mission survives. The people do not.'}
  }),

  bunker: mkEpisode({
    id:'bunker',title:'The Bunker',subtitle:'Episode 5',tagline:'The door is sealed. The truth is buried deeper.',venueDefault:'Barfly Social The Bunker',createButton:'Create Bunker',joinVerb:'Enter Bunker',playerNoun:'Occupant',groupName:'Bunker',chatTitle:'Bunker Chat',systemAlias:'Bunker System',finalThreat:'The Protocol',finalIntroTitle:'Bunker Protocol',finalIntroText:'A red light fills the bunker. The old protocol activates. The system has decided there may be too many people inside.',statLabels:{hunger:'Food',hydration:'Air Safety',energy:'Stamina',willToLive:'Panic Control',personalEscapeAdvantage:'Surface Advantage',personalFinalBonus:'Override Bonus'},groupStatLabels:{campSafety:'Door Integrity',fire:'Generator Power',foodSupply:'Food Supply',waterSupply:'Air Quality',escapeProgress:'Surface Exit Progress',threatAwareness:'Protocol Knowledge',cluesFound:'Hidden Records',finalEncounterBonus:'Override Bonus',hiddenThreatLevel:'System Pressure'},cardWords:{resource:'ration pack',tool:'maintenance key',signal:'surface receiver',clue:'old evacuation record',place:'the sealed door'},
    roles:[{id:'medic',name:'Medic',ability:'Stabilize',description:'Treats sickness and panic.'},{id:'builder',name:'Technician',ability:'Repair System',description:'Improves generator, air, and doors.'},{id:'scout',name:'Investigator',ability:'Search Records',description:'Finds hidden rooms and records with less danger.'},{id:'hunter',name:'Security',ability:'Control Access',description:'Prevents sabotage and protects supplies.'},{id:'negotiator',name:'Counselor',ability:'Calm Panic',description:'Repairs trust and willpower.'},{id:'skeptic',name:'Organizer',ability:'Audit the Plan',description:'Detects false protocol claims and bad ration math.'}],
    rounds:[
      {number:1,title:'The Sealed Door',publicEvent:'Six people wake inside a sealed bunker. No one remembers hearing the door lock.',groupGoal:'Secure the bunker and understand the controls.',choices:{help_group:choice('Inspect Controls','Protocol Knowledge rises.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Claim a Bunk','Panic control rises, trust drops.',{personalStat:'willToLive',personalGain:2,trustCost:1}),take_risk:choice('Pry Open a Panel','Possible record or injury.',{energyCost:2,rewardStat:'fire',rewardGain:1,injuryChance:.30,clueChance:.55,clueText:'A hidden counter shows the bunker has run this protocol before.'})},teamBonus:{threshold:3,stat:'campSafety',amount:1,text:'The group secures the main door and control wall.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The system detects disorder immediately.'}},
      {number:2,title:'Rationing Begins',publicEvent:'The food and water are not enough for a long stay.',groupGoal:'Create a fair ration plan.',choices:{help_group:choice('Build a Ration Plan','Food Supply rises. Trust rises.',{energyCost:1,groupStat:'foodSupply',groupGain:1}),help_self:choice('Hide Rations','Food improves. Trust drops.',{personalStat:'hunger',personalGain:2,trustCost:1,groupStat:'foodSupply',groupLoss:1}),take_risk:choice('Search Storage Crawlspace','Possible supplies or record.',{energyCost:2,rewardStat:'foodSupply',rewardGain:2,injuryChance:.35,clueChance:.50,clueText:'A previous ration chart has names crossed out before supplies ran out.'})},teamBonus:{threshold:3,stat:'foodSupply',amount:2,text:'The ration plan buys the group time.'},failure:{threshold:1,stat:'trustPressure',amount:1,text:'Ration arguments split the bunker.'}},
      {number:3,title:'Air Gets Thin',publicEvent:'The ventilation system stutters. The air tastes metallic.',groupGoal:'Repair air filtration.',choices:{help_group:choice('Repair Ventilation','Air Quality rises.',{energyCost:2,groupStat:'waterSupply',groupGain:1}),help_self:choice('Keep an Air Mask','Air safety rises. Trust drops.',{personalStat:'hydration',personalGain:2,trustCost:2}),take_risk:choice('Enter the Vent Shaft','Possible fix, high danger.',{energyCost:2,groupStat:'waterSupply',groupGain:1,injuryChance:.45,clueChance:.55,clueText:'Inside the vent is a scratch mark: the protocol lies.'})},teamBonus:{threshold:3,stat:'waterSupply',amount:2,text:'The air system stabilizes.'},failure:{threshold:2,stat:'hiddenThreatLevel',amount:1,text:'The system begins emergency rationing of air.'}},
      {number:4,title:'The Hidden Room',publicEvent:'A wall panel opens to a room not on the map.',groupGoal:'Learn why the bunker was built.',choices:{help_group:choice('Search Records Together','Hidden Records rise.',{energyCost:1,groupStat:'cluesFound',groupGain:1}),help_self:choice('Keep a File Secret','Override bonus rises, trust drops.',{personalFinalBonus:2,trustCost:1}),take_risk:choice('Power the Old Terminal','Possible truth, possible system response.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,injuryChance:.35,clueChance:.65,clueText:'The bunker was built to test compliance, not only survival.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'The group understands more of the bunker protocol.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The system keeps its secrets.'}},
      {number:5,title:'The Vote',publicEvent:'The system suggests reducing the number of occupants to extend survival.',groupGoal:'Reject or control the system’s pressure.',choices:{help_group:choice('Refuse the Vote','Trust and protocol knowledge rise.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Campaign Against Someone','Your panic control rises, trust drops hard.',{personalStat:'willToLive',personalGain:1,trustCost:2}),take_risk:choice('Hack the Vote Module','Override bonus may rise.',{energyCost:2,finalBonusGain:1,injuryChance:.35,clueChance:.60,clueText:'The vote is designed to make occupants eliminate each other.'})},teamBonus:{threshold:3,stat:'trustPressure',amount:-1,text:'The group refuses to let the system divide them.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The protocol gains control of the room.'}},
      {number:6,title:'The Surface Signal',publicEvent:'A surface signal comes through. Opening the door could save everyone or kill everyone.',groupGoal:'Override the protocol or prepare to open the door.',choices:{help_group:choice('Prepare the Surface Exit','Surface Exit Progress rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:2}),help_self:choice('Prepare a Private Exit','Surface advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Override the Protocol','Override bonus may rise, high danger.',{energyCost:2,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The protocol fails when occupants refuse to sacrifice each other.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The surface exit is ready.'},trapBonus:{threshold:2,amount:2,text:'The override is strong enough to challenge the system.'}}
    ],
    finalChoices:{fight_together:{label:'Override Together',description:'Best with trust and protocol knowledge.'},set_trap:{label:'Loop the Protocol',description:'Best with hidden records and override bonus.'},run_raft:{label:'Open the Surface Door',description:'Best if surface exit progress is high.'},sacrifice:{label:'Take the System Lock',description:'May save others while trapping you.'},betray_group:{label:'Lock Others Out',description:'May save you but lets the protocol win.'}},
    outcomes:{full:'Protocol Overridden',broken:'Surface Escape',partial:'A Few Reach the Surface',wounded:'One Leaves the Bunker',lost:'The Bunker Chooses'},
    endingTexts:{full:'The occupants override the protocol together. The bunker door opens without a sacrifice.',broken:'Some reach the surface, but the bunker keeps part of the group below.',partial:'A few escape through the door while alarms bury the truth.',wounded:'One person reaches the surface and cannot forget who was left inside.',lost:'The system wins. The bunker survives by choosing for them.'}
  }),

  heist: mkEpisode({
    id:'heist',title:'Bank Heist Gone Wrong',subtitle:'Episode 6',tagline:'The score was easy. Escaping each other is the hard part.',venueDefault:'Barfly Social Bank Heist',createButton:'Create Heist',joinVerb:'Join Crew',playerNoun:'Crew Member',groupName:'Crew',chatTitle:'Crew Chat',systemAlias:'Police Scanner',finalThreat:'The Police Breach',finalIntroTitle:'The Getaway',finalIntroText:'The lobby glass explodes. The police breach has begun. The crew has one final choice: loyalty, money, or survival.',statLabels:{hunger:'Nerve',hydration:'Ammo',energy:'Stamina',willToLive:'Cool',personalEscapeAdvantage:'Getaway Advantage',personalFinalBonus:'Leverage'},groupStatLabels:{campSafety:'Crew Control',fire:'Cameras / Comms',foodSupply:'Cash Bags',waterSupply:'Ammo Pool',escapeProgress:'Getaway Progress',threatAwareness:'Informant Intel',cluesFound:'Evidence Found',finalEncounterBonus:'Getaway Bonus',hiddenThreatLevel:'Police Pressure'},cardWords:{resource:'cash bundle',tool:'keycard',signal:'police scanner',clue:'informant note',place:'the vault door'},
    roles:[{id:'medic',name:'Patch',ability:'Stop the Bleeding',description:'Softens injury and keeps the crew moving.'},{id:'builder',name:'Hacker',ability:'Open Systems',description:'Improves cameras, vault, and getaway progress.'},{id:'scout',name:'Driver',ability:'Fast Route',description:'Risky escape moves are safer.'},{id:'hunter',name:'Enforcer',ability:'Control the Room',description:'Protects crew control and ammo.'},{id:'negotiator',name:'Smooth Talker',ability:'Lower Heat',description:'Repairs trust and reduces panic.'},{id:'skeptic',name:'Insider',ability:'Spot the Setup',description:'Finds informant clues and fake stories.'}],
    rounds:[
      {number:1,title:'The Vault Job',publicEvent:'The crew enters the bank and starts the robbery. The plan is clean — at first.',groupGoal:'Control the room and open the vault.',choices:{help_group:choice('Control the Lobby','Crew Control rises.',{energyCost:1,groupStat:'campSafety',groupGain:1}),help_self:choice('Pocket Loose Cash','Nerve rises, trust drops.',{personalStat:'hunger',personalGain:2,trustCost:1,groupStat:'foodSupply',groupLoss:1}),take_risk:choice('Rush the Vault Door','Possible cash progress, possible injury.',{energyCost:2,groupStat:'foodSupply',groupGain:1,injuryChance:.30,clueChance:.50,clueText:'The vault timer was changed before the crew arrived.'})},teamBonus:{threshold:3,stat:'campSafety',amount:2,text:'The crew controls the lobby without chaos.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The messy start raises police pressure.'}},
      {number:2,title:'Alarm Triggered',publicEvent:'The alarm sounds. Police arrive faster than expected.',groupGoal:'Cut cameras and keep the plan alive.',choices:{help_group:choice('Kill Cameras','Comms control rises.',{energyCost:1,groupStat:'fire',groupGain:1}),help_self:choice('Secure Your Exit Bag','Getaway advantage rises, trust drops.',{personalEscapeGain:1,trustCost:1}),take_risk:choice('Tap the Police Scanner','Possible intel, possible exposure.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,injuryChance:.30,clueChance:.55,clueText:'Police knew the crew count before the alarm triggered.'})},teamBonus:{threshold:3,stat:'fire',amount:2,text:'The crew gets camera control back.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'Police pressure rises with every camera angle.'}},
      {number:3,title:'The Missing Bag',publicEvent:'One bag of cash disappears before the crew reaches the vault exit.',groupGoal:'Find the bag without turning on the crew.',choices:{help_group:choice('Search Together','Evidence found rises. Trust rises.',{energyCost:1,groupStat:'cluesFound',groupGain:1}),help_self:choice('Hide Your Cut','Leverage rises, trust drops.',{personalFinalBonus:2,trustCost:2}),take_risk:choice('Check the Back Hall','Possible bag or informant clue.',{energyCost:2,rewardStat:'foodSupply',rewardGain:1,injuryChance:.35,clueChance:.60,clueText:'A burner phone is taped under the hall table.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'The crew finds evidence that someone leaked the job.'},failure:{threshold:1,stat:'trustPressure',amount:1,text:'The missing bag splits the crew.'}},
      {number:4,title:'Informant Rumor',publicEvent:'A police negotiator knows details only the crew should know.',groupGoal:'Identify the leak or stop the paranoia.',choices:{help_group:choice('Compare the Plan','Informant Intel rises.',{energyCost:1,groupStat:'threatAwareness',groupGain:1}),help_self:choice('Blame a Rival','Your cool rises, trust drops hard.',{personalStat:'willToLive',personalGain:1,trustCost:2}),take_risk:choice('Trace the Burner Phone','Possible proof, high risk.',{energyCost:2,groupStat:'threatAwareness',groupGain:1,injuryChance:.40,clueChance:.65,clueText:'The phone has one outgoing message: breach when they split.'})},teamBonus:{threshold:2,stat:'threatAwareness',amount:1,text:'The crew narrows the informant window.'},failure:{threshold:1,stat:'hiddenThreatLevel',amount:1,text:'The rumor does the police work for them.'}},
      {number:5,title:'The Escape Route',publicEvent:'The original getaway alley is blocked. The crew needs a new exit.',groupGoal:'Create a new escape route.',choices:{help_group:choice('Open the Service Tunnel','Getaway Progress rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:1}),help_self:choice('Cut a Side Deal','Getaway advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Move Through the Roof','Possible route, sniper risk.',{energyCost:2,groupStat:'escapeProgress',groupGain:1,injuryChance:.45,clueChance:.55,clueText:'The roof team was sent before the crew announced demands.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The crew opens a real getaway path.'},failure:{threshold:1,stat:'escapeProgress',amount:-1,text:'The escape path gets worse.'}},
      {number:6,title:'Final Negotiation',publicEvent:'Police offer a deal. The vault is open. The breach team is moving.',groupGoal:'Decide whether to escape together or sell someone out.',choices:{help_group:choice('Coordinate the Getaway','Getaway Progress rises.',{energyCost:2,groupStat:'escapeProgress',groupGain:2}),help_self:choice('Prepare to Cut a Deal','Getaway advantage rises, trust drops.',{personalEscapeGain:2,trustCost:2}),take_risk:choice('Expose the Informant','Getaway bonus may rise, injury risk high.',{energyCost:2,finalBonusGain:1,injuryChance:.50,clueChance:.70,clueText:'The police breach depends on the crew betraying each other first.'})},teamBonus:{threshold:3,stat:'escapeProgress',amount:2,text:'The crew can still escape as a unit.'},trapBonus:{threshold:2,amount:2,text:'The informant plan is exposed enough to use against the police.'}}
    ],
    finalChoices:{fight_together:{label:'Escape Together',description:'Best if crew loyalty and getaway progress are high.'},set_trap:{label:'Expose the Informant',description:'Best with informant intel and evidence.'},run_raft:{label:'Run the Getaway',description:'Best if getaway progress is high.'},sacrifice:{label:'Take the Fall',description:'May save the crew but gets you caught.'},betray_group:{label:'Cut a Deal',description:'May save you but can doom the crew.'}},
    outcomes:{full:'Clean Getaway',broken:'Dirty Getaway',partial:'Few Escape with Cash',wounded:'The Informant Wins, One Gets Out',lost:'Everyone Gets Caught'},
    endingTexts:{full:'The crew escapes together with the score and exposes the setup.',broken:'Some escape with money, but sirens follow the crew forever.',partial:'Only a few make it out through smoke, cash, and betrayal.',wounded:'The informant gets the deal. One crew member slips away with the story.',lost:'Greed destroys the crew before the police finish the breach.'}
  })
};

function getEpisode(id) { return episodes[id] || episodes.island; }
function episodeSummaries() { return Object.values(episodes).map(e => ({ id: e.id, title: e.title, subtitle: e.subtitle, tagline: e.tagline, finalThreat: e.finalThreat, venueDefault: e.venueDefault })); }

module.exports = { episodes, getEpisode, episodeSummaries };
